from __future__ import annotations

from ..common import ROOT

BANNER = "Generated by tools/codegen/led_font. Do not edit."
SOURCE = ROOT / "fonts" / "led_bitmap_font.json"
LABEL = "led font"

OUTPUTS = {
    ROOT / "firmware/components/led/include/led_font_generated.hpp": "cpp",
    ROOT / "configurator/src/shared/led-font.ts": "typescript",
}
