from __future__ import annotations

from ..common import ROOT

BANNER = "Generated by tools/codegen/ui_strings. Do not edit."
SOURCE = ROOT / "i18n"
LABEL = "ui strings"
BASE_LOCALE = "en"
TARGET = ROOT / "configurator/src/shared"
