from __future__ import annotations

from ..common import ROOT

BANNER = "Generated by tools/codegen/configuration_schema. Do not edit."
SOURCE = ROOT / "configuration" / "configuration_schema.json"
OUTPUTS = {
    ROOT
    / "firmware/services/configuration_contract/include/application_configuration_generated.hpp": "cpp_contract",
    ROOT
    / "firmware/services/configuration/include/configuration_schema_generated.hpp": "cpp_parser",
    ROOT / "configurator/src/shared/configuration-schema.ts": "typescript",
    ROOT / "docs/configuration-schema.md": "markdown",
}
