// Generated by tools/generate_configuration_schema.py. Do not edit.

export type RgbColor = `#${string}`

export const CONFIGURATION_SCHEMA_VERSION = 3

/** Maximum compact JSON payload in bytes, for both the wire and NVS. */
export const MAXIMUM_PAYLOAD_SIZE = 16384
/** Dashboard screens. Raising this multiplies per-screen widget storage and requires an explicit RAM-budget review. */
export const MAXIMUM_SCREENS = 1
/** Ordered widget references per screen. Bounds the sum of every widget variant on one screen. */
export const MAXIMUM_WIDGETS_PER_SCREEN = 17
/** Text widget storage per screen. */
export const MAXIMUM_TEXT_WIDGETS = 16
/** Delta Time widget storage per screen. */
export const MAXIMUM_DELTA_TIME_WIDGETS = 1
/** Value modifiers per text widget. */
export const MAXIMUM_VALUE_MODIFIERS = 4
/** Widget identifier storage including the terminator (15 usable bytes). */
export const WIDGET_ID_CAPACITY = 16
/** Widget title text storage including the terminator (15 usable bytes). */
export const WIDGET_TITLE_CAPACITY = 16
/** Placeholder text storage including the terminator (15 usable bytes). */
export const UNAVAILABLE_TEXT_CAPACITY = 16
/** Delta Time placeholder storage including the terminator (15 usable bytes). */
export const DELTA_TIME_TEXT_CAPACITY = 16
/** Storage for the dotted property path reported with a rejection, including the terminator. */
export const VALIDATION_PATH_CAPACITY = 48
/** Canonical telemetry field name storage including the terminator (39 usable bytes). Must match CANONICAL_NAME_CAPACITY in tools/generate_telemetry_catalog.py. */
export const VALUE_BINDING_CAPACITY = 40

/** Immutable hardware identity. Must match the firmware build or the configuration is rejected. */
export type BoardId = 't_display_s3' | 'guition_esp32_4848s040' | 'guition_jc1060p470c'
export const BOARD_ID_VALUES: readonly BoardId[] = ['t_display_s3', 'guition_esp32_4848s040', 'guition_jc1060p470c']

/** Telemetry transport selection. board_default defers to the immutable board descriptor. */
export type TelemetryTransportId = 'board_default' | 'native_usb_cdc' | 'uart'
export const TELEMETRY_TRANSPORT_ID_VALUES: readonly TelemetryTransportId[] = ['board_default', 'native_usb_cdc', 'uart']

/** What the Delta Time widget shows while its telemetry is unavailable. */
export type DeltaTimeUnavailableBehavior = 'hide' | 'placeholder' | 'zero'
export const DELTA_TIME_UNAVAILABLE_BEHAVIOR_VALUES: readonly DeltaTimeUnavailableBehavior[] = ['hide', 'placeholder', 'zero']

/** Horizontal alignment of a text widget value. */
export type TextAlignment = 'left' | 'center' | 'right'
export const TEXT_ALIGNMENT_VALUES: readonly TextAlignment[] = ['left', 'center', 'right']

/** Presentation transform applied after the modifier pipeline. */
export type ValueTransformType = 'none' | 'time'
export const VALUE_TRANSFORM_TYPE_VALUES: readonly ValueTransformType[] = ['none', 'time']

/** Stateful value processing implemented by a module behind the pipeline callback. */
export type ValueModifierType = 'lap_timer'
export const VALUE_MODIFIER_TYPE_VALUES: readonly ValueModifierType[] = ['lap_timer']

/** Widget kind discriminator. Selects the compile-time widget descriptor used to build the widget. */
export type WidgetType = 'text' | 'delta_time'
export const WIDGET_TYPE_VALUES: readonly WidgetType[] = ['text', 'delta_time']

export interface FontSpec {
  family?: string
  size_px?: number
}

export interface TimeTransform {
  format?: 'duration_ms' | 'signed_duration_ms'
  prefix?: string
  suffix?: string
}

export interface BoardConfiguration {
  board: BoardId
}

/** Reserved bounded peripheral section. No user-configurable peripheral driver has a complete production contract yet, so a non-empty list is rejected rather than guessed. */
export type HardwareConfiguration = readonly never[]

export interface UartTelemetryConfiguration {
  port?: number
  tx_pin?: number
  rx_pin?: number
  baud_rate?: number
  silence_esp_logs?: boolean
}

export interface TelemetryTransportConfiguration {
  id?: TelemetryTransportId
  uart?: UartTelemetryConfiguration
}

export interface DeltaTimeScaleConfiguration {
  enabled?: boolean
  show_sign?: boolean
  range_ms?: number
}

/** Delta Time module configuration. Distinct from the Delta Time widget, which owns presentation only. */
export interface DeltaTimeConfiguration {
  unavailable_behavior?: DeltaTimeUnavailableBehavior
  placeholder?: string
  scale?: DeltaTimeScaleConfiguration
}

/** Absolute geometry in logical screen pixels. */
export interface WidgetPlacement {
  x?: number
  y?: number
  width?: number
  height?: number
}

export interface WidgetInsets {
  left?: number
  top?: number
  right?: number
  bottom?: number
}

export interface WidgetBorder {
  color?: RgbColor
  width_px?: number
  radius_px?: number
}

export interface WidgetTitleStyle {
  text?: string
  font?: FontSpec
  color?: RgbColor
  offset_y_px?: number
}

export interface WidgetValueStyle {
  font?: FontSpec
  color?: RgbColor
  alignment?: TextAlignment
  unavailable_text?: string
}

/** Stateless presentation transform. Absent means no transform is applied. */
export interface ValueTransform extends TimeTransform {
  type?: ValueTransformType
}

export interface ValueModifier {
  type?: ValueModifierType
}

export interface DeltaTimeScaleStyle {
  vertical_padding_px?: number
  border_width_px?: number
  border_radius_px?: number
}

/** Renders Delta Time module state. Requires the delta_time module section to be present. */
export interface DeltaTimeWidgetConfiguration {
  type: 'delta_time'
  id?: string
  font?: FontSpec
  placement?: WidgetPlacement
  z_index?: number
  faster_color?: RgbColor
  slower_color?: RgbColor
  neutral_color?: RgbColor
  scale?: DeltaTimeScaleStyle
}

/** Reusable telemetry text widget. Consumes one canonical binding through a pre-bound typed callback. */
export interface TextWidgetConfiguration {
  type: 'text'
  id?: string
  binding?: string
  modifiers?: ValueModifier[]
  transform?: ValueTransform
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  value?: WidgetValueStyle
  background_color?: RgbColor
}

/** One dashboard screen. A screen is the coordinate space for the widgets it owns. */
export interface ScreenConfiguration {
  id?: string
  background_color?: RgbColor
  widgets?: WidgetConfiguration[]
}

export interface DashboardConfiguration {
  screens?: ScreenConfiguration[]
}

export interface ApplicationConfiguration {
  board: BoardId
  hardware?: HardwareConfiguration
  telemetry_transport?: TelemetryTransportConfiguration
  delta_time?: DeltaTimeConfiguration
  dashboard?: DashboardConfiguration
}

/** Discriminated widget union. Adding a widget type adds one member here. */
export type WidgetConfiguration = DeltaTimeWidgetConfiguration | TextWidgetConfiguration

export const WIDGET_TYPES: readonly string[] = ['delta_time', 'text']

/** Property names accepted inside each object, mirroring the firmware allow-lists. */
export const SCHEMA_OBJECT_KEYS: Record<string, readonly string[]> = {
  BoardConfiguration: ['board'],
  UartTelemetryConfiguration: ['port', 'tx_pin', 'rx_pin', 'baud_rate', 'silence_esp_logs'],
  TelemetryTransportConfiguration: ['id', 'uart'],
  DeltaTimeScaleConfiguration: ['enabled', 'show_sign', 'range_ms'],
  DeltaTimeConfiguration: ['unavailable_behavior', 'placeholder', 'scale'],
  WidgetPlacement: ['x', 'y', 'width', 'height'],
  WidgetInsets: ['left', 'top', 'right', 'bottom'],
  WidgetBorder: ['color', 'width_px', 'radius_px'],
  WidgetTitleStyle: ['text', 'font', 'color', 'offset_y_px'],
  WidgetValueStyle: ['font', 'color', 'alignment', 'unavailable_text'],
  ValueTransform: ['type', 'format', 'prefix', 'suffix'],
  ValueModifier: ['type'],
  DeltaTimeScaleStyle: ['vertical_padding_px', 'border_width_px', 'border_radius_px'],
  DeltaTimeWidgetConfiguration: ['type', 'id', 'font', 'placement', 'z_index', 'faster_color', 'slower_color', 'neutral_color', 'scale'],
  TextWidgetConfiguration: ['type', 'id', 'binding', 'modifiers', 'transform', 'placement', 'z_index', 'padding', 'border', 'title', 'value', 'background_color'],
  ScreenConfiguration: ['id', 'background_color', 'widgets'],
  DashboardConfiguration: ['screens'],
  ApplicationConfiguration: ['board', 'hardware', 'telemetry_transport', 'delta_time', 'dashboard'],
}

/**
 * Nested object type for each property, so a validator can walk an unknown
 * document without a hand-maintained mapping.
 */
export const SCHEMA_CHILD_TYPES: Record<string, Record<string, string>> = {
  TelemetryTransportConfiguration: { uart: 'UartTelemetryConfiguration' },
  DeltaTimeConfiguration: { scale: 'DeltaTimeScaleConfiguration' },
  WidgetTitleStyle: { font: 'FontSpec' },
  WidgetValueStyle: { font: 'FontSpec' },
  DeltaTimeWidgetConfiguration: { font: 'FontSpec', placement: 'WidgetPlacement', scale: 'DeltaTimeScaleStyle' },
  TextWidgetConfiguration: { modifiers: 'ValueModifier', transform: 'ValueTransform', placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', value: 'WidgetValueStyle' },
  DashboardConfiguration: { screens: 'ScreenConfiguration' },
  ApplicationConfiguration: { hardware: 'HardwareConfiguration', telemetry_transport: 'TelemetryTransportConfiguration', delta_time: 'DeltaTimeConfiguration', dashboard: 'DashboardConfiguration' },
}

/** Bounded string capacities. Values include the terminator the firmware stores. */
export const TEXT_CAPACITIES: Record<string, number> = {
  'DeltaTimeConfiguration.placeholder': 16,
  'WidgetTitleStyle.text': 16,
  'WidgetValueStyle.unavailable_text': 16,
  'DeltaTimeWidgetConfiguration.id': 16,
  'TextWidgetConfiguration.id': 16,
  'TextWidgetConfiguration.binding': 40,
  'ScreenConfiguration.id': 16,
}
