// Generated by tools/generate_configuration_schema.py. Do not edit.

export type RgbColor = `#${string}`

export const CONFIGURATION_SCHEMA_VERSION = 4

/** Maximum compact JSON payload in bytes, for both the wire and NVS. Sized so a screen filled to every per-type cap still fits with room to spare; the buffers it sizes and the parser's document both live in external memory. */
export const MAXIMUM_PAYLOAD_SIZE = 65536
/** Dashboard screens. Raising this multiplies per-screen widget storage and requires an explicit RAM-budget review. */
export const MAXIMUM_SCREENS = 1
/** Ordered widget references per screen. Exactly the sum of every per-type cap below, so it never rejects a widget the typed storage accepted; it exists because the z-order table needs a size. What actually bounds a screen is kMaximumPayloadSize. */
export const MAXIMUM_WIDGETS_PER_SCREEN = 71
/** Text widget storage per screen. */
export const MAXIMUM_TEXT_WIDGETS = 16
/** Shape widget storage per screen. Shapes carry a dashboard's layout, so this is the most generous cap. */
export const MAXIMUM_SHAPE_WIDGETS = 24
/** Bar widget storage per screen. */
export const MAXIMUM_BAR_WIDGETS = 16
/** Arc widget storage per screen. */
export const MAXIMUM_ARC_WIDGETS = 8
/** Indicator strip storage per screen. */
export const MAXIMUM_INDICATOR_WIDGETS = 4
/** Graph storage per screen. Each instance owns a sample ring buffer, which is why this cap is the smallest. */
export const MAXIMUM_GRAPH_WIDGETS = 2
/** Delta Time widget storage per screen. */
export const MAXIMUM_DELTA_TIME_WIDGETS = 1
/** Segments in one indicator strip. */
export const MAXIMUM_INDICATOR_SEGMENTS = 16
/** Samples one graph retains. The ring buffer is sized by this whatever point_count asks for. */
export const MAXIMUM_GRAPH_POINTS = 128
/** Telemetry sources one text widget composes into a single string. Raising this grows the per-widget document storage, the widget render state, and the binder arrays. */
export const MAXIMUM_TEXT_SOURCES = 3
/** Value modifiers per text widget source. */
export const MAXIMUM_VALUE_MODIFIERS = 4
/** Conditional styling rules per widget. Four covers a normal, caution, warning and limit band. */
export const MAXIMUM_WIDGET_CONDITIONS = 4
/** Widget identifier storage including the terminator (15 usable bytes). */
export const WIDGET_ID_CAPACITY = 16
/** Widget title text storage including the terminator (15 usable bytes). */
export const WIDGET_TITLE_CAPACITY = 16
/** Placeholder text storage including the terminator (15 usable bytes). */
export const UNAVAILABLE_TEXT_CAPACITY = 16
/** Delta Time placeholder storage including the terminator (15 usable bytes). */
export const DELTA_TIME_TEXT_CAPACITY = 16
/** Storage for the dotted property path reported with a rejection, including the terminator. */
export const VALIDATION_PATH_CAPACITY = 48
/** Canonical telemetry field name storage including the terminator (39 usable bytes). Must match CANONICAL_NAME_CAPACITY in tools/generate_telemetry_catalog.py. */
export const VALUE_BINDING_CAPACITY = 40
/** Transform prefix and suffix storage including the terminator (15 usable bytes). */
export const VALUE_AFFIX_CAPACITY = 16

/** Immutable hardware identity. Must match the firmware build or the configuration is rejected. */
export type BoardId = 't_display_s3' | 'guition_esp32_4848s040' | 'guition_jc1060p470c'
export const BOARD_ID_VALUES: readonly BoardId[] = ['t_display_s3', 'guition_esp32_4848s040', 'guition_jc1060p470c']

/** Telemetry transport selection. board_default defers to the immutable board descriptor. */
export type TelemetryTransportId = 'board_default' | 'native_usb_cdc' | 'uart'
export const TELEMETRY_TRANSPORT_ID_VALUES: readonly TelemetryTransportId[] = ['board_default', 'native_usb_cdc', 'uart']

/** What the Delta Time widget shows while its telemetry is unavailable. */
export type DeltaTimeUnavailableBehavior = 'hide' | 'placeholder' | 'zero'
export const DELTA_TIME_UNAVAILABLE_BEHAVIOR_VALUES: readonly DeltaTimeUnavailableBehavior[] = ['hide', 'placeholder', 'zero']

/** Horizontal alignment of a text widget value. */
export type TextAlignment = 'left' | 'center' | 'right'
export const TEXT_ALIGNMENT_VALUES: readonly TextAlignment[] = ['left', 'center', 'right']

/** Presentation transform applied after the modifier pipeline. */
export type ValueTransformType = 'none' | 'time' | 'number'
export const VALUE_TRANSFORM_TYPE_VALUES: readonly ValueTransformType[] = ['none', 'time', 'number']

/** Comparison a styling rule applies to the numeric value of its condition source. */
export type ConditionOperator = 'above' | 'at_or_above' | 'below' | 'at_or_below' | 'equal' | 'not_equal'
export const CONDITION_OPERATOR_VALUES: readonly ConditionOperator[] = ['above', 'at_or_above', 'below', 'at_or_below', 'equal', 'not_equal']

/** Stateful value processing implemented by a module behind the pipeline callback. */
export type ValueModifierType = 'lap_timer'
export const VALUE_MODIFIER_TYPE_VALUES: readonly ValueModifierType[] = ['lap_timer']

/** Widget kind discriminator. Selects the compile-time widget descriptor used to build the widget. */
export type WidgetType = 'text' | 'delta_time'
export const WIDGET_TYPE_VALUES: readonly WidgetType[] = ['text', 'delta_time']

export interface FontSpec {
  family?: string
  size_px?: number
}

export interface TimeTransform {
  format?: 'duration_ms' | 'signed_duration_ms'
}

export interface NumberTransform {
  decimals?: number
  scale?: number
  offset?: number
}

export interface BoardConfiguration {
  board: BoardId
}

/** Reserved bounded peripheral section. No user-configurable peripheral driver has a complete production contract yet, so a non-empty list is rejected rather than guessed. */
export type HardwareConfiguration = readonly never[]

export interface UartTelemetryConfiguration {
  port?: number
  tx_pin?: number
  rx_pin?: number
  baud_rate?: number
  silence_esp_logs?: boolean
}

export interface TelemetryTransportConfiguration {
  id?: TelemetryTransportId
  uart?: UartTelemetryConfiguration
}

export interface DeltaTimeScaleConfiguration {
  enabled?: boolean
  show_sign?: boolean
  range_ms?: number
}

/** Delta Time module configuration. Distinct from the Delta Time widget, which owns presentation only. */
export interface DeltaTimeConfiguration {
  unavailable_behavior?: DeltaTimeUnavailableBehavior
  placeholder?: string
  scale?: DeltaTimeScaleConfiguration
}

/** Absolute geometry in logical screen pixels. */
export interface WidgetPlacement {
  x?: number
  y?: number
  width?: number
  height?: number
}

export interface WidgetInsets {
  left?: number
  top?: number
  right?: number
  bottom?: number
}

export interface WidgetBorder {
  color?: RgbColor
  width_px?: number
  radius_px?: number
}

export interface WidgetTitleStyle {
  text?: string
  font?: FontSpec
  color?: RgbColor
  offset_y_px?: number
}

export interface WidgetValueStyle {
  font?: FontSpec
  color?: RgbColor
  alignment?: TextAlignment
  unavailable_text?: string
}

/** Stateless presentation transform. Absent means no transform is applied. The prefix and suffix belong to the transform rather than to one type, so they also apply to an untransformed value. */
export interface ValueTransform extends TimeTransform, NumberTransform {
  type?: ValueTransformType
  prefix?: string
  suffix?: string
}

export interface ValueModifier {
  type?: ValueModifierType
}

export interface DeltaTimeScaleStyle {
  vertical_padding_px?: number
  border_width_px?: number
  border_radius_px?: number
}

/** Renders Delta Time module state. Requires the delta_time module section to be present. */
export interface DeltaTimeWidgetConfiguration {
  type: 'delta_time'
  id?: string
  font?: FontSpec
  placement?: WidgetPlacement
  z_index?: number
  faster_color?: RgbColor
  slower_color?: RgbColor
  neutral_color?: RgbColor
  scale?: DeltaTimeScaleStyle
}

/** Telemetry a widget watches to style itself, independent of what it displays: a gear readout can turn red on engine speed. It carries no transform because a condition consumes the typed value rather than its presentation. */
export interface ConditionSourceConfiguration {
  binding?: string
  modifiers?: ValueModifier[]
}

/** One styling rule. The first rule whose comparison holds describes the widget; whatever it leaves unset stays as the widget's static style, and a transparent colour means unset rather than see-through. */
export interface WidgetCondition {
  op?: ConditionOperator
  value?: number
  color?: RgbColor
  background_color?: RgbColor
  border_color?: RgbColor
  hidden?: boolean
  blink_ms?: number
  hold_ms?: number
}

/** One canonical telemetry source of a text widget, consumed through a pre-bound typed callback. Its transform affixes are what separate it from the next source, so composing several needs no format string. */
export interface TextSourceConfiguration {
  binding?: string
  modifiers?: ValueModifier[]
  transform?: ValueTransform
}

/** What every widget type owns regardless of what it draws: where it sits, how it is boxed, and the rules that restyle it. Flattened into each widget, so these are plain widget properties on the wire. */
export interface WidgetFrame {
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  background_color?: RgbColor
  background_inset_px?: number
  condition_source?: ConditionSourceConfiguration
  conditions?: WidgetCondition[]
}

/** Reusable telemetry text widget. Renders its ordered sources as one string. */
export interface TextWidgetConfiguration {
  type: 'text'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  background_color?: RgbColor
  background_inset_px?: number
  condition_source?: ConditionSourceConfiguration
  conditions?: WidgetCondition[]
  sources?: TextSourceConfiguration[]
  title?: WidgetTitleStyle
  value?: WidgetValueStyle
}

/** One dashboard screen. A screen is the coordinate space for the widgets it owns. */
export interface ScreenConfiguration {
  id?: string
  background_color?: RgbColor
  widgets?: WidgetConfiguration[]
}

export interface DashboardConfiguration {
  screens?: ScreenConfiguration[]
}

export interface ApplicationConfiguration {
  board: BoardId
  hardware?: HardwareConfiguration
  telemetry_transport?: TelemetryTransportConfiguration
  delta_time?: DeltaTimeConfiguration
  dashboard?: DashboardConfiguration
}

/** Discriminated widget union. Adding a widget type adds one member here. */
export type WidgetConfiguration = DeltaTimeWidgetConfiguration | TextWidgetConfiguration

export const WIDGET_TYPES: readonly string[] = ['delta_time', 'text']

/** Property names accepted inside each object, mirroring the firmware allow-lists. */
export const SCHEMA_OBJECT_KEYS: Record<string, readonly string[]> = {
  BoardConfiguration: ['board'],
  UartTelemetryConfiguration: ['port', 'tx_pin', 'rx_pin', 'baud_rate', 'silence_esp_logs'],
  TelemetryTransportConfiguration: ['id', 'uart'],
  DeltaTimeScaleConfiguration: ['enabled', 'show_sign', 'range_ms'],
  DeltaTimeConfiguration: ['unavailable_behavior', 'placeholder', 'scale'],
  WidgetPlacement: ['x', 'y', 'width', 'height'],
  WidgetInsets: ['left', 'top', 'right', 'bottom'],
  WidgetBorder: ['color', 'width_px', 'radius_px'],
  WidgetTitleStyle: ['text', 'font', 'color', 'offset_y_px'],
  WidgetValueStyle: ['font', 'color', 'alignment', 'unavailable_text'],
  ValueTransform: ['type', 'format', 'decimals', 'scale', 'offset', 'prefix', 'suffix'],
  ValueModifier: ['type'],
  DeltaTimeScaleStyle: ['vertical_padding_px', 'border_width_px', 'border_radius_px'],
  DeltaTimeWidgetConfiguration: ['type', 'id', 'font', 'placement', 'z_index', 'faster_color', 'slower_color', 'neutral_color', 'scale'],
  ConditionSourceConfiguration: ['binding', 'modifiers'],
  WidgetCondition: ['op', 'value', 'color', 'background_color', 'border_color', 'hidden', 'blink_ms', 'hold_ms'],
  TextSourceConfiguration: ['binding', 'modifiers', 'transform'],
  WidgetFrame: ['id', 'placement', 'z_index', 'padding', 'border', 'background_color', 'background_inset_px', 'condition_source', 'conditions'],
  TextWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'background_color', 'background_inset_px', 'condition_source', 'conditions', 'sources', 'title', 'value'],
  ScreenConfiguration: ['id', 'background_color', 'widgets'],
  DashboardConfiguration: ['screens'],
  ApplicationConfiguration: ['board', 'hardware', 'telemetry_transport', 'delta_time', 'dashboard'],
}

/**
 * Nested object type for each property, so a validator can walk an unknown
 * document without a hand-maintained mapping.
 */
export const SCHEMA_CHILD_TYPES: Record<string, Record<string, string>> = {
  TelemetryTransportConfiguration: { uart: 'UartTelemetryConfiguration' },
  DeltaTimeConfiguration: { scale: 'DeltaTimeScaleConfiguration' },
  WidgetTitleStyle: { font: 'FontSpec' },
  WidgetValueStyle: { font: 'FontSpec' },
  DeltaTimeWidgetConfiguration: { font: 'FontSpec', placement: 'WidgetPlacement', scale: 'DeltaTimeScaleStyle' },
  ConditionSourceConfiguration: { modifiers: 'ValueModifier' },
  TextSourceConfiguration: { modifiers: 'ValueModifier', transform: 'ValueTransform' },
  WidgetFrame: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', condition_source: 'ConditionSourceConfiguration', conditions: 'WidgetCondition' },
  TextWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', condition_source: 'ConditionSourceConfiguration', conditions: 'WidgetCondition', sources: 'TextSourceConfiguration', title: 'WidgetTitleStyle', value: 'WidgetValueStyle' },
  DashboardConfiguration: { screens: 'ScreenConfiguration' },
  ApplicationConfiguration: { hardware: 'HardwareConfiguration', telemetry_transport: 'TelemetryTransportConfiguration', delta_time: 'DeltaTimeConfiguration', dashboard: 'DashboardConfiguration' },
}

/** Bounded string capacities. Values include the terminator the firmware stores. */
export const TEXT_CAPACITIES: Record<string, number> = {
  'DeltaTimeConfiguration.placeholder': 16,
  'WidgetTitleStyle.text': 16,
  'WidgetValueStyle.unavailable_text': 16,
  'ValueTransform.prefix': 16,
  'ValueTransform.suffix': 16,
  'DeltaTimeWidgetConfiguration.id': 16,
  'ConditionSourceConfiguration.binding': 40,
  'TextSourceConfiguration.binding': 40,
  'WidgetFrame.id': 16,
  'ScreenConfiguration.id': 16,
}
