// Generated by tools/generate_configuration_schema.py. Do not edit.

export type RgbColor = `#${string}`

export const CONFIGURATION_SCHEMA_VERSION = 5

/** Maximum compact JSON payload in bytes, for both the wire and NVS. Sized so a screen filled to every per-type cap still fits with room to spare; the buffers it sizes and the parser's document both live in external memory. */
export const MAXIMUM_PAYLOAD_SIZE = 65536
/** Dashboard screens. Widget storage is a dashboard-wide pool, so a screen costs only its reference table. */
export const MAXIMUM_SCREENS = 1
/** Ordered widget references per screen. Exactly the sum of every per-type cap below, so one screen can hold the whole pool; what bounds the widgets across every screen is the pool itself, and what bounds a document is kMaximumPayloadSize. */
export const MAXIMUM_WIDGETS_PER_SCREEN = 94
/** Text widget storage for the whole dashboard. A dense dashboard spends most of its widgets here: a tyre quadrant alone is eight readouts. */
export const MAXIMUM_TEXT_WIDGETS = 32
/** Shape widget storage for the whole dashboard. Shapes carry a dashboard's layout, so this is the most generous cap. */
export const MAXIMUM_SHAPE_WIDGETS = 24
/** Bar widget storage for the whole dashboard. */
export const MAXIMUM_BAR_WIDGETS = 16
/** Arc widget storage for the whole dashboard. */
export const MAXIMUM_ARC_WIDGETS = 8
/** Indicator strip storage for the whole dashboard. */
export const MAXIMUM_INDICATOR_WIDGETS = 4
/** Graph storage for the whole dashboard. Each instance owns a sample ring buffer, which is why this cap is the smallest. */
export const MAXIMUM_GRAPH_WIDGETS = 2
/** Image widget storage for the whole dashboard. */
export const MAXIMUM_IMAGE_WIDGETS = 8
/** Segments in one indicator strip. */
export const MAXIMUM_INDICATOR_SEGMENTS = 16
/** Samples one graph retains. The ring buffer is sized by this whatever point_count asks for. */
export const MAXIMUM_GRAPH_POINTS = 128
/** Telemetry sources one text widget composes into a single string. Raising this grows the per-widget document storage, the widget render state, and the binder arrays. */
export const MAXIMUM_TEXT_SOURCES = 3
/** Value modifiers per text widget source. */
export const MAXIMUM_VALUE_MODIFIERS = 4
/** Stops in one widget colour ramp. Four is a normal, caution, warning and limit band, the same bands the conditional rules cover discretely. */
export const MAXIMUM_COLOR_STOPS = 4
/** Conditional styling rules per widget. Four covers a normal, caution, warning and limit band. */
export const MAXIMUM_WIDGET_CONDITIONS = 4
/** Uploaded image identifier storage including the terminator (31 usable bytes). Must match kImageIdCapacity in the image contract. */
export const IMAGE_ID_CAPACITY = 32
/** Widget identifier storage including the terminator (15 usable bytes). */
export const WIDGET_ID_CAPACITY = 16
/** Widget title text storage including the terminator (15 usable bytes). */
export const WIDGET_TITLE_CAPACITY = 16
/** Placeholder text storage including the terminator (15 usable bytes). */
export const UNAVAILABLE_TEXT_CAPACITY = 16
/** Storage for the dotted property path reported with a rejection, including the terminator. */
export const VALIDATION_PATH_CAPACITY = 48
/** Canonical telemetry field name storage including the terminator (39 usable bytes). Must match CANONICAL_NAME_CAPACITY in tools/generate_telemetry_catalog.py. */
export const VALUE_BINDING_CAPACITY = 40
/** Transform prefix and suffix storage including the terminator (15 usable bytes). */
export const VALUE_AFFIX_CAPACITY = 16

/** Immutable hardware identity. Must match the firmware build or the configuration is rejected. */
export type BoardId = 't_display_s3' | 'guition_esp32_4848s040' | 'guition_jc1060p470c'
export const BOARD_ID_VALUES: readonly BoardId[] = ['t_display_s3', 'guition_esp32_4848s040', 'guition_jc1060p470c']

/** Telemetry transport selection. board_default defers to the immutable board descriptor. */
export type TelemetryTransportId = 'board_default' | 'native_usb_cdc' | 'uart'
export const TELEMETRY_TRANSPORT_ID_VALUES: readonly TelemetryTransportId[] = ['board_default', 'native_usb_cdc', 'uart']

/** Horizontal alignment of a text widget value. */
export type TextAlignment = 'left' | 'center' | 'right'
export const TEXT_ALIGNMENT_VALUES: readonly TextAlignment[] = ['left', 'center', 'right']

/** Presentation transform applied after the modifier pipeline. */
export type ValueTransformType = 'none' | 'time' | 'number'
export const VALUE_TRANSFORM_TYPE_VALUES: readonly ValueTransformType[] = ['none', 'time', 'number']

/** Axis a linear gradient runs along. Only used when a gradient colour is set. */
export type GradientDirection = 'horizontal' | 'vertical'
export const GRADIENT_DIRECTION_VALUES: readonly GradientDirection[] = ['horizontal', 'vertical']

/** Which part of a widget the colour ramp paints. What content means is the widget type's own business: text paints its label, a bar its fill. */
export type ColorRampTarget = 'content' | 'background' | 'border'
export const COLOR_RAMP_TARGET_VALUES: readonly ColorRampTarget[] = ['content', 'background', 'border']

/** Comparison a styling rule applies to the numeric value of its condition source. */
export type ConditionOperator = 'above' | 'at_or_above' | 'below' | 'at_or_below' | 'equal' | 'not_equal'
export const CONDITION_OPERATOR_VALUES: readonly ConditionOperator[] = ['above', 'at_or_above', 'below', 'at_or_below', 'equal', 'not_equal']

/** Stateful value processing implemented by a module behind the pipeline callback. */
export type ValueModifierType = 'lap_timer'
export const VALUE_MODIFIER_TYPE_VALUES: readonly ValueModifierType[] = ['lap_timer']

/** Axis a bar fills along. A vertical bar grows upwards unless it is inverted. */
export type BarOrientation = 'horizontal' | 'vertical'
export const BAR_ORIENTATION_VALUES: readonly BarOrientation[] = ['horizontal', 'vertical']

/** Outline a shape widget takes. A line is a thin rectangle, so it needs no kind of its own. */
export type ShapeKind = 'rectangle' | 'ellipse'
export const SHAPE_KIND_VALUES: readonly ShapeKind[] = ['rectangle', 'ellipse']

/** Widget kind discriminator. Selects the compile-time widget descriptor used to build the widget. */
export type WidgetType = 'text' | 'shape' | 'bar' | 'arc' | 'indicator' | 'graph' | 'image'
export const WIDGET_TYPE_VALUES: readonly WidgetType[] = ['text', 'shape', 'bar', 'arc', 'indicator', 'graph', 'image']

export interface FontSpec {
  family?: string
  size_px?: number
}

export interface TimeTransform {
  format?: 'duration_ms' | 'signed_duration_ms'
}

export interface NumberTransform {
  decimals?: number
  scale?: number
  offset?: number
}

export interface BoardConfiguration {
  board: BoardId
}

/** Reserved bounded peripheral section. No user-configurable peripheral driver has a complete production contract yet, so a non-empty list is rejected rather than guessed. */
export type HardwareConfiguration = readonly never[]

export interface UartTelemetryConfiguration {
  port?: number
  tx_pin?: number
  rx_pin?: number
  baud_rate?: number
  silence_esp_logs?: boolean
}

export interface TelemetryTransportConfiguration {
  id?: TelemetryTransportId
  uart?: UartTelemetryConfiguration
}

/** Absolute geometry in logical screen pixels. */
export interface WidgetPlacement {
  x?: number
  y?: number
  width?: number
  height?: number
}

export interface WidgetInsets {
  left?: number
  top?: number
  right?: number
  bottom?: number
}

export interface WidgetBorder {
  color?: RgbColor
  width_px?: number
  radius_px?: number
}

export interface WidgetTitleStyle {
  text?: string
  font?: FontSpec
  color?: RgbColor
  offset_y_px?: number
}

export interface WidgetValueStyle {
  font?: FontSpec
  color?: RgbColor
  alignment?: TextAlignment
  unavailable_text?: string
}

/** Stateless presentation transform. Absent means no transform is applied. The prefix and suffix belong to the transform rather than to one type, so they also apply to an untransformed value. */
export interface ValueTransform extends TimeTransform, NumberTransform {
  type?: ValueTransformType
  prefix?: string
  suffix?: string
}

export interface ValueModifier {
  type?: ValueModifierType
}

/** A canonical telemetry binding with its modifier pipeline, consumed as a typed value. Carries no transform: the widgets that read one map it through a range or compare it, rather than presenting it as text. */
export interface ValueSourceConfiguration {
  binding?: string
  modifiers?: ValueModifier[]
}

/** One anchor of a colour ramp. */
export interface ColorStop {
  at?: number
  color?: RgbColor
}

/** A colour interpolated from the watched source rather than switched by a threshold. It is the base layer: a matching rule paints over it, and with no stops the authored colour stands. */
export interface ColorRamp {
  target?: ColorRampTarget
  stops?: ColorStop[]
}

/** One styling rule. The first rule whose comparison holds describes the widget; whatever it leaves unset stays as the widget's static style, and a transparent colour means unset rather than see-through. */
export interface WidgetCondition {
  op?: ConditionOperator
  value?: number
  color?: RgbColor
  background_color?: RgbColor
  border_color?: RgbColor
  hidden?: boolean
  blink_ms?: number
  hold_ms?: number
}

/** One canonical telemetry source of a text widget, consumed through a pre-bound typed callback. Its transform affixes are what separate it from the next source, so composing several needs no format string. */
export interface TextSourceConfiguration {
  binding?: string
  modifiers?: ValueModifier[]
  transform?: ValueTransform
}

/** What every widget type owns regardless of what it draws: where it sits, how it is boxed, and the rules that restyle it. Flattened into each widget, so these are plain widget properties on the wire. */
export interface WidgetFrame {
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
}

/** Reusable telemetry text widget. Renders its ordered sources as one string. */
export interface TextWidgetConfiguration {
  type: 'text'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  sources?: TextSourceConfiguration[]
  value?: WidgetValueStyle
}

/** Input window a widget maps its source through. The fraction is clamped, so a value outside the window reads as full or empty rather than overflowing. */
export interface ValueRange {
  minimum?: number
  maximum?: number
}

/** One telemetry source drawn as a filled proportion of the widget. The frame background is the track the fill runs over, so a bar needs no track colour of its own. */
export interface BarWidgetConfiguration {
  type: 'bar'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  source?: ValueSourceConfiguration
  minimum?: number
  maximum?: number
  origin?: number
  orientation?: BarOrientation
  inverted?: boolean
  fill_color?: RgbColor
  fill_grad_color?: RgbColor
}

/** One telemetry source swept around an arc. The track is the arc's own background, so a gauge needs no shape behind it. */
export interface ArcWidgetConfiguration {
  type: 'arc'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  source?: ValueSourceConfiguration
  minimum?: number
  maximum?: number
  start_angle_deg?: number
  sweep_deg?: number
  thickness_px?: number
  track_color?: RgbColor
  fill_color?: RgbColor
  inverted?: boolean
}

/** One lamp in an indicator strip. */
export interface IndicatorSegment {
  threshold?: number
  color?: RgbColor
}

/** A row of lamps that light as one telemetry source climbs its range: shift lights, a rev strip, a stint marker. */
export interface IndicatorWidgetConfiguration {
  type: 'indicator'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  source?: ValueSourceConfiguration
  minimum?: number
  maximum?: number
  orientation?: BarOrientation
  segment_gap_px?: number
  segment_radius_px?: number
  off_color?: RgbColor
  blink_threshold?: number
  blink_ms?: number
  segments?: IndicatorSegment[]
}

/** A rolling trace of one telemetry source. The history is presentation state the widget samples for itself; it is not a telemetry value and nothing else can read it. */
export interface GraphWidgetConfiguration {
  type: 'graph'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  source?: ValueSourceConfiguration
  minimum?: number
  maximum?: number
  point_count?: number
  sample_interval_ms?: number
  line_color?: RgbColor
  line_width_px?: number
}

/** An uploaded image drawn inside the frame. It binds no telemetry of its own, but its styling rules can hide it, flash it or recolour it. Neither scaled nor rotated: the configurator converts each image to the size it is drawn at, which also keeps the accelerated draw path on the ESP32-P4. */
export interface ImageWidgetConfiguration {
  type: 'image'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  image?: string
  recolor?: RgbColor
  recolor_opa?: number
}

/** Panels, dividers and backing plates: the frame is the whole widget. It binds no telemetry of its own, but its styling rules can still hide it or flash it. A line is a thin rectangle. */
export interface ShapeWidgetConfiguration {
  type: 'shape'
  id?: string
  placement?: WidgetPlacement
  z_index?: number
  padding?: WidgetInsets
  border?: WidgetBorder
  title?: WidgetTitleStyle
  background_color?: RgbColor
  background_grad_color?: RgbColor
  background_grad_dir?: GradientDirection
  background_inset_px?: number
  condition_source?: ValueSourceConfiguration
  color_ramp?: ColorRamp
  conditions?: WidgetCondition[]
  kind?: ShapeKind
}

/** One dashboard screen: the coordinate space its widgets are placed in, and the order they stack in. The widgets themselves live in the dashboard's pool; a screen names them by reference. */
export interface ScreenConfiguration {
  id?: string
  background_color?: RgbColor
  widgets?: WidgetConfiguration[]
}

/** Owns the typed widget storage as one pool shared by every screen; a screen holds only an ordered list of references into it. A screen therefore costs its reference table rather than a full set of widget arrays. */
export interface DashboardConfiguration {
  screens?: ScreenConfiguration[]
}

export interface ApplicationConfiguration {
  board: BoardId
  hardware?: HardwareConfiguration
  telemetry_transport?: TelemetryTransportConfiguration
  dashboard?: DashboardConfiguration
}

/** Discriminated widget union. Adding a widget type adds one member here. */
export type WidgetConfiguration = ArcWidgetConfiguration | BarWidgetConfiguration | GraphWidgetConfiguration | ImageWidgetConfiguration | IndicatorWidgetConfiguration | ShapeWidgetConfiguration | TextWidgetConfiguration

export const WIDGET_TYPES: readonly string[] = ['text', 'bar', 'arc', 'indicator', 'graph', 'image', 'shape']

/** Property names accepted inside each object, mirroring the firmware allow-lists. */
export const SCHEMA_OBJECT_KEYS: Record<string, readonly string[]> = {
  BoardConfiguration: ['board'],
  UartTelemetryConfiguration: ['port', 'tx_pin', 'rx_pin', 'baud_rate', 'silence_esp_logs'],
  TelemetryTransportConfiguration: ['id', 'uart'],
  WidgetPlacement: ['x', 'y', 'width', 'height'],
  WidgetInsets: ['left', 'top', 'right', 'bottom'],
  WidgetBorder: ['color', 'width_px', 'radius_px'],
  WidgetTitleStyle: ['text', 'font', 'color', 'offset_y_px'],
  WidgetValueStyle: ['font', 'color', 'alignment', 'unavailable_text'],
  ValueTransform: ['type', 'format', 'decimals', 'scale', 'offset', 'prefix', 'suffix'],
  ValueModifier: ['type'],
  ValueSourceConfiguration: ['binding', 'modifiers'],
  ColorStop: ['at', 'color'],
  ColorRamp: ['target', 'stops'],
  WidgetCondition: ['op', 'value', 'color', 'background_color', 'border_color', 'hidden', 'blink_ms', 'hold_ms'],
  TextSourceConfiguration: ['binding', 'modifiers', 'transform'],
  WidgetFrame: ['id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions'],
  TextWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'sources', 'value'],
  ValueRange: ['minimum', 'maximum'],
  BarWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'source', 'minimum', 'maximum', 'origin', 'orientation', 'inverted', 'fill_color', 'fill_grad_color'],
  ArcWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'source', 'minimum', 'maximum', 'start_angle_deg', 'sweep_deg', 'thickness_px', 'track_color', 'fill_color', 'inverted'],
  IndicatorSegment: ['threshold', 'color'],
  IndicatorWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'source', 'minimum', 'maximum', 'orientation', 'segment_gap_px', 'segment_radius_px', 'off_color', 'blink_threshold', 'blink_ms', 'segments'],
  GraphWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'source', 'minimum', 'maximum', 'point_count', 'sample_interval_ms', 'line_color', 'line_width_px'],
  ImageWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'image', 'recolor', 'recolor_opa'],
  ShapeWidgetConfiguration: ['type', 'id', 'placement', 'z_index', 'padding', 'border', 'title', 'background_color', 'background_grad_color', 'background_grad_dir', 'background_inset_px', 'condition_source', 'color_ramp', 'conditions', 'kind'],
  ScreenConfiguration: ['id', 'background_color', 'widgets'],
  DashboardConfiguration: ['screens'],
  ApplicationConfiguration: ['board', 'hardware', 'telemetry_transport', 'dashboard'],
}

/** Struct that carries each widget variant, keyed by its discriminator. */
export const SCHEMA_WIDGET_STRUCTS: Record<string, string> = { text: 'TextWidgetConfiguration', bar: 'BarWidgetConfiguration', arc: 'ArcWidgetConfiguration', indicator: 'IndicatorWidgetConfiguration', graph: 'GraphWidgetConfiguration', image: 'ImageWidgetConfiguration', shape: 'ShapeWidgetConfiguration' }

/**
 * Nested object type for each property, so a validator can walk an unknown
 * document without a hand-maintained mapping.
 */
export const SCHEMA_CHILD_TYPES: Record<string, Record<string, string>> = {
  TelemetryTransportConfiguration: { uart: 'UartTelemetryConfiguration' },
  WidgetTitleStyle: { font: 'FontSpec' },
  WidgetValueStyle: { font: 'FontSpec' },
  ValueSourceConfiguration: { modifiers: 'ValueModifier' },
  ColorRamp: { stops: 'ColorStop' },
  TextSourceConfiguration: { modifiers: 'ValueModifier', transform: 'ValueTransform' },
  WidgetFrame: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition' },
  TextWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition', sources: 'TextSourceConfiguration', value: 'WidgetValueStyle' },
  BarWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition', source: 'ValueSourceConfiguration' },
  ArcWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition', source: 'ValueSourceConfiguration' },
  IndicatorWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition', source: 'ValueSourceConfiguration', segments: 'IndicatorSegment' },
  GraphWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition', source: 'ValueSourceConfiguration' },
  ImageWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition' },
  ShapeWidgetConfiguration: { placement: 'WidgetPlacement', padding: 'WidgetInsets', border: 'WidgetBorder', title: 'WidgetTitleStyle', condition_source: 'ValueSourceConfiguration', color_ramp: 'ColorRamp', conditions: 'WidgetCondition' },
  DashboardConfiguration: { screens: 'ScreenConfiguration' },
  ApplicationConfiguration: { hardware: 'HardwareConfiguration', telemetry_transport: 'TelemetryTransportConfiguration', dashboard: 'DashboardConfiguration' },
}

/** Bounded string capacities. Values include the terminator the firmware stores. */
export const TEXT_CAPACITIES: Record<string, number> = {
  'WidgetTitleStyle.text': 16,
  'WidgetValueStyle.unavailable_text': 16,
  'ValueTransform.prefix': 16,
  'ValueTransform.suffix': 16,
  'ValueSourceConfiguration.binding': 40,
  'TextSourceConfiguration.binding': 40,
  'WidgetFrame.id': 16,
  'TextWidgetConfiguration.id': 16,
  'BarWidgetConfiguration.id': 16,
  'ArcWidgetConfiguration.id': 16,
  'IndicatorWidgetConfiguration.id': 16,
  'GraphWidgetConfiguration.id': 16,
  'ImageWidgetConfiguration.id': 16,
  'ImageWidgetConfiguration.image': 32,
  'ShapeWidgetConfiguration.id': 16,
  'ScreenConfiguration.id': 16,
}
