from __future__ import annotations

from typing import Any


def generate_cpp(document: dict[str, Any], fields: list[dict[str, str]]) -> str:
    descriptors = "\n".join(
        f'    {{"{field["name"]}", ValueType::{field["type"]}}},'
        for field in fields
    )
    return f"""// Generated by tools/codegen/telemetry_catalog. Do not edit.
#pragma once

namespace simcore::telemetry::catalog {{

inline constexpr std::size_t kFieldCount = {len(fields)};
inline constexpr std::size_t kMaximumFieldCount = {document['maximum_fields']};

inline constexpr std::array<FieldDescriptor, kFieldCount> kFieldDescriptors{{{{
{descriptors}
}}}};

static_assert(kFieldCount <= kMaximumFieldCount);

}}
"""
