from __future__ import annotations

from typing import Any

from .constants import UNAVAILABLE_OPERATORS

CONVERSIONS = {
    "number": "Number",
    "text": "Text",
    "boolean": "Boolean",
    "timespan_ms": "TimespanMs",
}

NEW_DATA_SEGMENT = ".GameData.NewData."


def literal(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def comparisons() -> list[str]:
    return ["None", *(pascal(operator) for operator in UNAVAILABLE_OPERATORS)]


def property_fallback(name: str) -> str | None:
    if NEW_DATA_SEGMENT not in name:
        return None
    return name.replace(NEW_DATA_SEGMENT, ".GameData.", 1)


def computations(mappings: dict[str, dict[str, Any]]) -> list[str]:
    names = {
        mapping["computed"] for mapping in mappings.values() if "computed" in mapping
    }
    return ["None", *sorted(names)]


def entry(field: dict[str, str], mapping: dict[str, Any]) -> str:
    name = mapping.get("property")
    computed = mapping.get("computed")
    rule = mapping.get("unavailable_when")
    parts = [
        literal(field["wire_id"]),
        literal(field["name"]),
        literal(name),
        literal(None if name is None else property_fallback(name)),
        f"FieldComputation.{computed or 'None'}",
        f"FieldConversion.{CONVERSIONS[mapping.get('conversion', 'number')]}",
        literal(mapping.get("format")),
        repr(float(mapping.get("scale", 1))),
        literal(mapping.get("fallback")),
        f"FieldComparison.{pascal(rule['op']) if rule else 'None'}",
        repr(float(rule["value"] if rule else 0)),
        f"FieldRate.{field['rate'].capitalize()}",
    ]
    return f"            new TelemetryField({', '.join(parts)}),"


def generate_csharp(
    profile: dict[str, Any],
    fields: list[dict[str, str]],
    mappings: dict[str, dict[str, Any]],
) -> str:
    link = profile["link"]
    frequencies = profile["frequencies"]
    entries = "\n".join(entry(field, mappings[field["name"]]) for field in fields)
    computation_names = ",\n        ".join(computations(mappings))
    comparison_names = ",\n        ".join(comparisons())
    return f"""// Generated by tools/codegen/telemetry_catalog. Do not edit.

namespace Pitrig.SimHub
{{
    internal enum FieldConversion
    {{
        Number,
        Text,
        Boolean,
        TimespanMs
    }}

    internal enum FieldRate
    {{
        Fast,
        Normal,
        Slow,
        Changes
    }}

    internal enum FieldComputation
    {{
        {computation_names}
    }}

    internal enum FieldComparison
    {{
        {comparison_names}
    }}

    internal sealed class TelemetryField
    {{
        public TelemetryField(
            string wireId,
            string name,
            string property,
            string propertyFallback,
            FieldComputation computation,
            FieldConversion conversion,
            string format,
            double scale,
            string fallback,
            FieldComparison unavailableWhen,
            double unavailableValue,
            FieldRate rate)
        {{
            WireId = wireId;
            Name = name;
            Property = property;
            PropertyFallback = propertyFallback;
            Computation = computation;
            Conversion = conversion;
            Format = format;
            Scale = scale;
            Fallback = fallback;
            UnavailableWhen = unavailableWhen;
            UnavailableValue = unavailableValue;
            Rate = rate;
        }}

        public string WireId {{ get; }}

        public string Name {{ get; }}

        public string Property {{ get; }}

        public string PropertyFallback {{ get; }}

        public FieldComputation Computation {{ get; }}

        public FieldConversion Conversion {{ get; }}

        public string Format {{ get; }}

        public double Scale {{ get; }}

        public string Fallback {{ get; }}

        public FieldComparison UnavailableWhen {{ get; }}

        public double UnavailableValue {{ get; }}

        public FieldRate Rate {{ get; }}
    }}

    internal static class TelemetryCatalog
    {{
        public const string LinkMagic = {literal(link["magic"])};

        public const byte LinkVersion = {link["version"]};

        public const int LinkDefaultPort = {link["port"]};

        public const int LinkSourcePort = {link["source_port"]};

        public const int LinkMaximumPayload = {link["maximum_payload"]};

        public const int LinkKeyframeIntervalMs = {link["keyframe_interval_ms"]};

        public const int FastHertz = {frequencies["fast"]};

        public const int NormalHertz = {frequencies["normal"]};

        public const int SlowHertz = {frequencies["slow"]};

        public static readonly TelemetryField[] Fields =
        {{
{entries}
        }};
    }}
}}
"""
