from __future__ import annotations

import json
from typing import Any


def identifier_key(identifier: str) -> int:
    first = ord(identifier[0])
    second = ord(identifier[1]) if len(identifier) == 2 else 0
    return (first << 8) | second


def generate_simhub(_document: dict[str, Any], fields: list[dict[str, str]]) -> str:
    descriptors = "\n".join(
        f'    {{"{field["wire_id"]}", "{field["name"]}"}},' for field in fields
    )
    lookup = sorted(
        (
            identifier_key(field["wire_id"]),
            index,
        )
        for index, field in enumerate(fields)
    )
    lookup_entries = "\n".join(
        f"    {{{key}, {index}}}," for key, index in lookup
    )
    return f"""// Generated by tools/codegen/telemetry_catalog. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace pitrig::protocols::simhub_catalog {{

struct BindingDescriptor {{
  std::string_view identifier;
  std::string_view canonical_name;
}};

struct LookupEntry {{
  std::uint16_t key;
  std::uint16_t binding_index;
}};

inline constexpr std::array<BindingDescriptor, {len(fields)}> kBindings{{{{
{descriptors}
}}}};

inline constexpr std::array<LookupEntry, {len(fields)}> kLookup{{{{
{lookup_entries}
}}}};

}}
"""


def generate_simhub_expression(
    field: dict[str, str], mapping: dict[str, Any]
) -> str:
    identifier = field["wire_id"]
    source = mapping.get("expression")
    if source is None:
        property_name = mapping["property"]
        source = f"[{property_name}]"
        new_data_segment = ".GameData.NewData."
        if new_data_segment in property_name:
            normalized_name = property_name.replace(
                new_data_segment, ".GameData.", 1
            )
            source = f"isnull({source}, [{normalized_name}])"
    conversion = mapping.get("conversion", "number")
    fallback = mapping.get("fallback")
    if conversion == "timespan_ms":
        converted = f"format(timespantoseconds({source}) * 1000, '0')"
    elif conversion == "boolean":
        converted = f"if({source}, '1', '0')"
    elif conversion == "text":
        converted = f"replace(replace('' + {source}, '\\r', ' '), '\\n', ' ')"
    else:
        scaled = source
        if "scale" in mapping:
            scaled = f"({source}) * {mapping['scale']}"
        converted = f"format({scaled}, '{mapping['format']}')"

    unavailable = f"'' + isnull({source}, '') = ''"
    if fallback is not None:
        converted = f"if({unavailable}, '{fallback}', {converted})"
        return f"'{identifier};' + {converted} + '\\n'"
    return (
        f"if({unavailable}, '{identifier};\\n', "
        f"'{identifier};' + {converted} + '\\n')"
    )


def generate_shsds(
    profile: dict[str, Any],
    fields: list[dict[str, str]],
    mappings: dict[str, dict[str, Any]],
) -> str:
    update_messages = []
    for field in fields:
        update_messages.append(
            {
                "Message": {
                    "Expression": generate_simhub_expression(
                        field, mappings[field["name"]]
                    )
                },
                "IsEnabled": True,
                "MaximumFrequency": profile["frequencies"][field["rate"]],
            }
        )
    document = {
        "AutomaticReconnect": True,
        "SerialPortName": "",
        "StartupDelayMs": 0,
        "IsConnecting": False,
        "IsEnabled": True,
        "LogIncomingData": False,
        "IsConnected": False,
        "BaudRate": profile["baud_rate"],
        "DtrEnable": False,
        "RtsEnable": False,
        "EditorExpanded": True,
        "Name": profile["name"],
        "Description": profile["description"],
        "LastErrorDate": "0001-01-01T00:00:00+00:00",
        "LastErrorMessage": None,
        "IsFreezed": False,
        "SettingsBuilder": {"Settings": [], "IsEditMode": False},
        "OnConnectMessage": {"Expression": ""},
        "OnDisconnectMessage": {"Expression": ""},
        "UpdateMessages": update_messages,
    }
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n"


def generate_simhub_typescript(
    profile: dict[str, Any],
    fields: list[dict[str, str]],
    mappings: dict[str, dict[str, Any]],
) -> str:
    defaults = {
        "name": profile["name"],
        "description": profile["description"],
        "baudRate": profile["baud_rate"],
    }
    link = {
        "magic": profile["link"]["magic"],
        "version": profile["link"]["version"],
        "port": profile["link"]["port"],
        "maximumPayload": profile["link"]["maximum_payload"],
        "keyframeIntervalMs": profile["link"]["keyframe_interval_ms"],
    }
    records = []
    for field in fields:
        record = {
            "name": field["name"],
            "expression": generate_simhub_expression(
                field, mappings[field["name"]]
            ),
            "maximumFrequency": profile["frequencies"][field["rate"]],
        }
        records.append(
            "  " + json.dumps(record, ensure_ascii=False, separators=(",", ":"))
        )
    body = ",\n".join(records)
    defaults_json = json.dumps(defaults, ensure_ascii=False, separators=(",", ":"))
    link_json = json.dumps(link, ensure_ascii=False, separators=(",", ":"))
    return f"""// Generated by tools/codegen/telemetry_catalog. Do not edit.

export interface SimHubProfileEntry {{
  name: string
  expression: string
  maximumFrequency: number
}}

export const SIMHUB_PROFILE_DEFAULTS = {defaults_json} as const

export const SIMHUB_LINK = {link_json} as const

export const SIMHUB_PROFILE_ENTRIES = [
{body}
] as const satisfies readonly SimHubProfileEntry[]
"""
