from __future__ import annotations

import json
from typing import Any

from .constants import CATEGORY_LABELS


def generate_typescript(
    _document: dict[str, Any], fields: list[dict[str, str]]
) -> str:
    records = []
    for field in fields:
        record = {
            "name": field["name"],
            "wireId": field["wire_id"],
            "type": field["type"],
            "unit": field["unit"],
            "category": field["category"],
            "categoryLabel": CATEGORY_LABELS[field["category"]],
            "rate": field["rate"],
            "availability": field["availability"],
            "description": field["description"],
        }
        records.append("  " + json.dumps(record, ensure_ascii=False, separators=(",", ":")))
    body = ",\n".join(records)
    return f"""// Generated by tools/codegen/telemetry_catalog. Do not edit.

export type TelemetryValueType = 'text' | 'uint32' | 'int32' | 'float32' | 'boolean'
export type TelemetryRate = 'fast' | 'normal' | 'slow' | 'changes'
export type TelemetryAvailability = 'common' | 'optional' | 'computed' | 'game_specific'

export interface TelemetryCatalogEntry {{
  name: string
  wireId: string
  type: TelemetryValueType
  unit: string
  category: string
  categoryLabel: string
  rate: TelemetryRate
  availability: TelemetryAvailability
  description: string
}}

export const TELEMETRY_CATALOG = [
{body}
] as const satisfies readonly TelemetryCatalogEntry[]
"""
