#pragma once

#include "sdkconfig.h"

#ifdef CONFIG_SIMCORE_DEBUG
#define SIMCORE_DEBUG 1
#else
#define SIMCORE_DEBUG 0
#endif
#ifdef CONFIG_SIMCORE_LAYOUT_DEBUG
#define SIMCORE_LAYOUT_DEBUG 1
#else
#define SIMCORE_LAYOUT_DEBUG 0
#endif
#ifdef CONFIG_SIMCORE_DEBUG_OVERLAY_FULL
#define SIMCORE_DEBUG_OVERLAY_FULL 1
#else
#define SIMCORE_DEBUG_OVERLAY_FULL 0
#endif
#ifdef CONFIG_SIMCORE_DEBUG_OVERLAY_FPS
#define SIMCORE_DEBUG_OVERLAY_FPS 1
#else
#define SIMCORE_DEBUG_OVERLAY_FPS 0
#endif
#define SIMCORE_DEBUG_OVERLAY \
  (SIMCORE_DEBUG && (SIMCORE_DEBUG_OVERLAY_FULL || SIMCORE_DEBUG_OVERLAY_FPS))
#ifdef CONFIG_SIMCORE_LOG_MODE_FULL
#define SIMCORE_LOG_MODE_FULL 1
#endif
#ifdef CONFIG_SIMCORE_DISPLAY_RENDER_DIRECT
#define SIMCORE_DISPLAY_RENDER_DIRECT 1
#else
#define SIMCORE_DISPLAY_RENDER_DIRECT 0
#endif

#ifdef CONFIG_SIMCORE_DISPLAY_RENDER_FULL
#define SIMCORE_DISPLAY_RENDER_FULL 1
#else
#define SIMCORE_DISPLAY_RENDER_FULL 0
#endif

#ifdef CONFIG_SIMCORE_DISPLAY_RENDER_FULL_STRIPS
#define SIMCORE_DISPLAY_RENDER_FULL_STRIPS 1
#else
#define SIMCORE_DISPLAY_RENDER_FULL_STRIPS 0
#endif

#define SIMCORE_DISPLAY_RENDER_TEAR_FREE                       \
  (SIMCORE_DISPLAY_RENDER_DIRECT || SIMCORE_DISPLAY_RENDER_FULL || \
   SIMCORE_DISPLAY_RENDER_FULL_STRIPS)

#define SIMCORE_COMMUNICATION_CORE 0
#define SIMCORE_RENDER_CORE 1
