#pragma once

#include "sdkconfig.h"

#define SIMCORE_DEBUG CONFIG_SIMCORE_DEBUG
#define SIMCORE_LAYOUT_DEBUG CONFIG_SIMCORE_LAYOUT_DEBUG
#ifdef CONFIG_SIMCORE_DEBUG_OVERLAY_FULL
#define SIMCORE_DEBUG_OVERLAY_FULL 1
#else
#define SIMCORE_DEBUG_OVERLAY_FULL 0
#endif
#ifdef CONFIG_SIMCORE_DEBUG_OVERLAY_FPS
#define SIMCORE_DEBUG_OVERLAY_FPS 1
#else
#define SIMCORE_DEBUG_OVERLAY_FPS 0
#endif
#ifdef CONFIG_SIMCORE_LOG_MODE_FULL
#define SIMCORE_LOG_MODE_FULL 1
#endif
#ifdef CONFIG_SIMCORE_SECOND_TELEMETRY_LINK
#define SIMCORE_SECOND_TELEMETRY_LINK 1
#else
#define SIMCORE_SECOND_TELEMETRY_LINK 0
#endif

#ifdef CONFIG_SIMCORE_SECOND_TELEMETRY_LINK_SILENCE_LOGS
#define SIMCORE_SECOND_TELEMETRY_LINK_SILENCE_LOGS 1
#else
#define SIMCORE_SECOND_TELEMETRY_LINK_SILENCE_LOGS 0
#endif

#define SIMCORE_COMMUNICATION_CORE 0
#define SIMCORE_RENDER_CORE 1
