<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Pitrig.SimHub</AssemblyName>
    <RootNamespace>Pitrig.SimHub</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.1.0</Version>
    <SimHubPath Condition="'$(SimHubPath)' == ''">C:\Program Files (x86)\SimHub</SimHubPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="GameReaderCommon">
      <HintPath>$(SimHubPath)\GameReaderCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SimHub.Plugins">
      <HintPath>$(SimHubPath)\SimHub.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
