// Generated by tools/codegen/telemetry_catalog. Do not edit.

namespace Pitrig.SimHub
{
    internal enum FieldConversion
    {
        Number,
        Text,
        Boolean,
        TimespanMs
    }

    internal enum FieldRate
    {
        Fast,
        Normal,
        Slow,
        Changes
    }

    internal enum FieldComputation
    {
        None,
        ClassPosition,
        EstimatedLapTime,
        FuelRequired,
        FuelTimeRemaining,
        FuelToAdd,
        GForceLateral,
        GForceLongitudinal,
        GForceVertical,
        GapAhead,
        GapBehind,
        GearNumber,
        LapsRemaining,
        LastLapDeltaBest,
        LiveDelta,
        RpmPercent,
        SectorDelta,
        SlipAngle,
        TurboPressure
    }

    internal enum FieldComparison
    {
        None,
        Below,
        AtOrBelow
    }

    internal sealed class TelemetryField
    {
        public TelemetryField(
            string wireId,
            string name,
            string property,
            string propertyFallback,
            FieldComputation computation,
            FieldConversion conversion,
            string format,
            double scale,
            string fallback,
            FieldComparison unavailableWhen,
            double unavailableValue,
            FieldRate rate)
        {
            WireId = wireId;
            Name = name;
            Property = property;
            PropertyFallback = propertyFallback;
            Computation = computation;
            Conversion = conversion;
            Format = format;
            Scale = scale;
            Fallback = fallback;
            UnavailableWhen = unavailableWhen;
            UnavailableValue = unavailableValue;
            Rate = rate;
        }

        public string WireId { get; }

        public string Name { get; }

        public string Property { get; }

        public string PropertyFallback { get; }

        public FieldComputation Computation { get; }

        public FieldConversion Conversion { get; }

        public string Format { get; }

        public double Scale { get; }

        public string Fallback { get; }

        public FieldComparison UnavailableWhen { get; }

        public double UnavailableValue { get; }

        public FieldRate Rate { get; }
    }

    internal static class TelemetryCatalog
    {
        public const string LinkMagic = "PT";

        public const byte LinkVersion = 1;

        public const int LinkDefaultPort = 45455;

        public const int LinkSourcePort = 45456;

        public const int LinkMaximumPayload = 1200;

        public const int LinkKeyframeIntervalMs = 1000;

        public const int FastHertz = 60;

        public const int NormalHertz = 20;

        public const int SlowHertz = 5;

        public static readonly TelemetryField[] Fields =
        {
            new TelemetryField("S", "vehicle.speed", "DataCorePlugin.GameData.NewData.SpeedKmh", "DataCorePlugin.GameData.SpeedKmh", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("00", "vehicle.throttle", "DataCorePlugin.GameData.NewData.Throttle", "DataCorePlugin.GameData.Throttle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("01", "vehicle.brake", "DataCorePlugin.GameData.NewData.Brake", "DataCorePlugin.GameData.Brake", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("02", "vehicle.clutch", "DataCorePlugin.GameData.NewData.Clutch", "DataCorePlugin.GameData.Clutch", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("03", "vehicle.handbrake", "DataCorePlugin.GameData.NewData.Handbrake", "DataCorePlugin.GameData.Handbrake", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("04", "vehicle.steering", "DataCorePlugin.GameData.NewData.SteeringInput", "DataCorePlugin.GameData.SteeringInput", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("05", "vehicle.steering_angle", "DataCorePlugin.GameData.NewData.SteeringWheelAngle", "DataCorePlugin.GameData.SteeringWheelAngle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("BB", "vehicle.brake_bias", "DataCorePlugin.GameData.BrakeBias", null, FieldComputation.None, FieldConversion.Number, "0.0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Normal),
            new TelemetryField("R", "engine.rpm", "DataCorePlugin.GameData.NewData.Rpms", "DataCorePlugin.GameData.Rpms", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("06", "engine.max_rpm", "DataCorePlugin.GameData.NewData.MaxRpm", "DataCorePlugin.GameData.MaxRpm", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("07", "engine.shift_rpm", "DataCorePlugin.GameData.NewData.CarSettings_CurrentGearRedLineRPM", "DataCorePlugin.GameData.CarSettings_CurrentGearRedLineRPM", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("08", "engine.rpm_percent", null, null, FieldComputation.RpmPercent, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("09", "engine.running", "DataCorePlugin.GameData.NewData.EngineStarted", "DataCorePlugin.GameData.EngineStarted", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0a", "engine.ignition", "DataCorePlugin.GameData.NewData.EngineIgnitionOn", "DataCorePlugin.GameData.EngineIgnitionOn", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0b", "engine.starter", "DataCorePlugin.GameData.NewData.StarterOn", "DataCorePlugin.GameData.StarterOn", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0c", "engine.water_temperature", "DataCorePlugin.GameData.NewData.WaterTemperature", "DataCorePlugin.GameData.WaterTemperature", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Slow),
            new TelemetryField("0d", "engine.oil_temperature", "DataCorePlugin.GameData.NewData.OilTemperature", "DataCorePlugin.GameData.OilTemperature", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Slow),
            new TelemetryField("0e", "engine.oil_pressure", "DataCorePlugin.GameData.NewData.OilPressure", "DataCorePlugin.GameData.OilPressure", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Slow),
            new TelemetryField("0f", "engine.turbo_pressure", null, null, FieldComputation.TurboPressure, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0g", "engine.turbo_level", "DataCorePlugin.GameData.NewData.TurboPercent", "DataCorePlugin.GameData.TurboPercent", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0h", "engine.torque", "DataCorePlugin.GameData.NewData.EngineTorque", "DataCorePlugin.GameData.EngineTorque", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0i", "engine.power", "DataCorePlugin.GameData.NewData.EnginePower", "DataCorePlugin.GameData.EnginePower", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0j", "engine.map", "DataCorePlugin.GameData.NewData.EngineMap", "DataCorePlugin.GameData.EngineMap", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("0k", "engine.damage", "DataCorePlugin.GameData.NewData.EngineDamage", "DataCorePlugin.GameData.EngineDamage", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("G", "transmission.gear", "DataCorePlugin.GameData.NewData.Gear", "DataCorePlugin.GameData.Gear", FieldComputation.None, FieldConversion.Text, null, 1.0, "N", FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0l", "transmission.gear_number", null, null, FieldComputation.GearNumber, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0m", "transmission.shifting", "DataCorePlugin.GameData.NewData.IsShifting", "DataCorePlugin.GameData.IsShifting", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("0n", "transmission.damage", "DataCorePlugin.GameData.NewData.TransmissionDamage", "DataCorePlugin.GameData.TransmissionDamage", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("0o", "session.lap.current", "DataCorePlugin.GameData.NewData.CurrentLap", "DataCorePlugin.GameData.CurrentLap", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("0p", "session.lap.total", "DataCorePlugin.GameData.NewData.TotalLaps", "DataCorePlugin.GameData.TotalLaps", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("0q", "session.lap.completed", "DataCorePlugin.GameData.NewData.CompletedLaps", "DataCorePlugin.GameData.CompletedLaps", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("L", "session.lap.current_time", "DataCorePlugin.GameData.NewData.CurrentLapTime", "DataCorePlugin.GameData.CurrentLapTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("0r", "session.lap.last_time", "DataCorePlugin.GameData.NewData.LastLapTime", "DataCorePlugin.GameData.LastLapTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("B", "session.lap.best_time", "DataCorePlugin.GameData.NewData.BestLapTime", "DataCorePlugin.GameData.BestLapTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("0s", "session.lap.session_best_time", "DataCorePlugin.GameData.NewData.SessionBestLapTime", "DataCorePlugin.GameData.SessionBestLapTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("P", "session.lap.estimated_time", null, null, FieldComputation.EstimatedLapTime, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("D", "session.lap.delta", null, null, FieldComputation.LiveDelta, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0t", "session.lap.delta_best", null, null, FieldComputation.LiveDelta, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0u", "session.lap.delta_session_best", null, null, FieldComputation.LiveDelta, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("LD", "session.lap.last_delta_best", null, null, FieldComputation.LastLapDeltaBest, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("0v", "session.lap.invalid", "DataCorePlugin.GameData.NewData.LapInvalidated", "DataCorePlugin.GameData.LapInvalidated", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0w", "session.lap.valid", "DataCorePlugin.GameData.NewData.IsLapValid", "DataCorePlugin.GameData.IsLapValid", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("0x", "session.sector.current", "DataCorePlugin.GameData.NewData.CurrentSectorIndex", "DataCorePlugin.GameData.CurrentSectorIndex", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Normal),
            new TelemetryField("0y", "session.sector.current_time", "DataCorePlugin.GameData.NewData.CurrentSectorTime", "DataCorePlugin.GameData.CurrentSectorTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("0z", "session.sector.1_time", "DataCorePlugin.GameData.NewData.Sector1Time", "DataCorePlugin.GameData.Sector1Time", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("10", "session.sector.2_time", "DataCorePlugin.GameData.NewData.Sector2Time", "DataCorePlugin.GameData.Sector2Time", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("11", "session.sector.3_time", "DataCorePlugin.GameData.NewData.CurrentLapSector3Time", "DataCorePlugin.GameData.CurrentLapSector3Time", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("12", "session.sector.1_best", "DataCorePlugin.GameData.NewData.Sector1BestTime", "DataCorePlugin.GameData.Sector1BestTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("13", "session.sector.2_best", "DataCorePlugin.GameData.NewData.Sector2BestTime", "DataCorePlugin.GameData.Sector2BestTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("14", "session.sector.3_best", "DataCorePlugin.GameData.NewData.Sector3BestTime", "DataCorePlugin.GameData.Sector3BestTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("15", "session.sector.delta", null, null, FieldComputation.SectorDelta, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("16", "track.position_percent", "DataCorePlugin.GameData.NewData.TrackPositionPercent", "DataCorePlugin.GameData.TrackPositionPercent", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("17", "session.type", "DataCorePlugin.GameData.NewData.SessionTypeName", "DataCorePlugin.GameData.SessionTypeName", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("18", "session.name", "DataCorePlugin.GameData.NewData.SessionName", "DataCorePlugin.GameData.SessionName", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("19", "session.phase", "DataCorePlugin.GameData.NewData.SessionPhase", "DataCorePlugin.GameData.SessionPhase", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1a", "session.position", "DataCorePlugin.GameData.NewData.Position", "DataCorePlugin.GameData.Position", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Normal),
            new TelemetryField("1b", "session.class_position", null, null, FieldComputation.ClassPosition, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Normal),
            new TelemetryField("1c", "session.participants", "DataCorePlugin.GameData.NewData.OpponentsCount", "DataCorePlugin.GameData.OpponentsCount", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("1d", "session.class_participants", "DataCorePlugin.GameData.NewData.PlayerClassOpponentsCount", "DataCorePlugin.GameData.PlayerClassOpponentsCount", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("1e", "session.time_elapsed", "DataCorePlugin.GameData.NewData.GuessedElaspedGameTime", "DataCorePlugin.GameData.GuessedElaspedGameTime", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("1f", "session.time_remaining", "DataCorePlugin.GameData.NewData.SessionTimeLeft", "DataCorePlugin.GameData.SessionTimeLeft", FieldComputation.None, FieldConversion.TimespanMs, null, 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("1g", "session.laps_remaining", null, null, FieldComputation.LapsRemaining, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Normal),
            new TelemetryField("1h", "session.is_timed", "DataCorePlugin.GameData.NewData.IsTimedRace", "DataCorePlugin.GameData.IsTimedRace", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1i", "session.finished", "DataCorePlugin.GameData.NewData.IsPlayerFinished", "DataCorePlugin.GameData.IsPlayerFinished", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1j", "session.checkered", "DataCorePlugin.GameData.NewData.IsCheckered", "DataCorePlugin.GameData.IsCheckered", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1k", "session.starting_grid_position", "DataCorePlugin.GameData.NewData.StartingPosition", "DataCorePlugin.GameData.StartingPosition", FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Changes),
            new TelemetryField("1l", "session.gap_ahead", null, null, FieldComputation.GapAhead, FieldConversion.Number, "0.000", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("1m", "session.gap_behind", null, null, FieldComputation.GapBehind, FieldConversion.Number, "0.000", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("1n", "session.gap_leader", "DataCorePlugin.GameData.NewData.GapToLeader", "DataCorePlugin.GameData.GapToLeader", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("F", "vehicle.fuel.level", "DataCorePlugin.GameData.NewData.Fuel", "DataCorePlugin.GameData.Fuel", FieldComputation.None, FieldConversion.Number, "0.0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("1o", "vehicle.fuel.percent", "DataCorePlugin.GameData.NewData.FuelPercent", "DataCorePlugin.GameData.FuelPercent", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("1p", "vehicle.fuel.capacity", "DataCorePlugin.GameData.NewData.MaxFuel", "DataCorePlugin.GameData.MaxFuel", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("FC", "vehicle.fuel.average_consumption", "DataCorePlugin.Computed.Fuel_LitersPerLap", null, FieldComputation.None, FieldConversion.Number, "0.0", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Slow),
            new TelemetryField("1q", "vehicle.fuel.current_consumption", "DataCorePlugin.Computed.Fuel_CurrentConsumption", null, FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("FL", "vehicle.fuel.laps_remaining", "DataCorePlugin.Computed.Fuel_RemainingLaps", null, FieldComputation.None, FieldConversion.Number, "0.0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("1r", "vehicle.fuel.time_remaining", null, null, FieldComputation.FuelTimeRemaining, FieldConversion.Number, "0", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Slow),
            new TelemetryField("1s", "vehicle.fuel.required_to_finish", null, null, FieldComputation.FuelRequired, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Slow),
            new TelemetryField("1t", "vehicle.fuel.to_add", null, null, FieldComputation.FuelToAdd, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.Below, 0.0, FieldRate.Slow),
            new TelemetryField("1u", "vehicle.fuel.last_lap_consumption", "DataCorePlugin.Computed.Fuel_LastLapConsumption", null, FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.AtOrBelow, 0.0, FieldRate.Changes),
            new TelemetryField("1v", "vehicle.energy.level", "DataCorePlugin.GameData.NewData.BatteryLevel", "DataCorePlugin.GameData.BatteryLevel", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("1w", "vehicle.energy.percent", "DataCorePlugin.GameData.NewData.BatteryPercent", "DataCorePlugin.GameData.BatteryPercent", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("1x", "vehicle.energy.deployment_mode", "DataCorePlugin.GameData.NewData.EnergyDeploymentMode", "DataCorePlugin.GameData.EnergyDeploymentMode", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1y", "vehicle.energy.recovery_mode", "DataCorePlugin.GameData.NewData.EnergyRecoveryMode", "DataCorePlugin.GameData.EnergyRecoveryMode", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("1z", "vehicle.energy.laps_remaining", "DataCorePlugin.GameData.NewData.BatteryLapsRemaining", "DataCorePlugin.GameData.BatteryLapsRemaining", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("T", "vehicle.aids.traction_control_level", "DataCorePlugin.GameData.TCLevel", null, FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("20", "vehicle.aids.traction_control_active", "DataCorePlugin.GameData.NewData.TCActive", "DataCorePlugin.GameData.TCActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("A", "vehicle.aids.abs_level", "DataCorePlugin.GameData.ABSLevel", null, FieldComputation.None, FieldConversion.Number, "0", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("21", "vehicle.aids.abs_active", "DataCorePlugin.GameData.NewData.ABSActive", "DataCorePlugin.GameData.ABSActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("22", "vehicle.aids.stability_control", "DataCorePlugin.GameData.NewData.StabilityControlLevel", "DataCorePlugin.GameData.StabilityControlLevel", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("23", "vehicle.pit_limiter.enabled", "DataCorePlugin.GameData.NewData.PitLimiterOn", "DataCorePlugin.GameData.PitLimiterOn", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("24", "vehicle.in_pit_lane", "DataCorePlugin.GameData.NewData.IsInPitLane", "DataCorePlugin.GameData.IsInPitLane", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("25", "vehicle.in_pit_box", "DataCorePlugin.GameData.NewData.IsInPitBox", "DataCorePlugin.GameData.IsInPitBox", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("26", "vehicle.pit_requested", "DataCorePlugin.GameData.NewData.PitRequested", "DataCorePlugin.GameData.PitRequested", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("27", "vehicle.drs.available", "DataCorePlugin.GameData.NewData.DRSAvailable", "DataCorePlugin.GameData.DRSAvailable", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("28", "vehicle.drs.active", "DataCorePlugin.GameData.NewData.DRSEnabled", "DataCorePlugin.GameData.DRSEnabled", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("29", "vehicle.push_to_pass.available", "DataCorePlugin.GameData.NewData.PushToPassAvailable", "DataCorePlugin.GameData.PushToPassAvailable", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2a", "vehicle.push_to_pass.active", "DataCorePlugin.GameData.NewData.PushToPassActive", "DataCorePlugin.GameData.PushToPassActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("2b", "vehicle.headlights", "DataCorePlugin.GameData.NewData.Headlights", "DataCorePlugin.GameData.Headlights", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("2c", "vehicle.wipers", "DataCorePlugin.GameData.NewData.Wipers", "DataCorePlugin.GameData.Wipers", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("2d", "vehicle.horn", "DataCorePlugin.GameData.NewData.Horn", "DataCorePlugin.GameData.Horn", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("2e", "vehicle.speed_limiter", "DataCorePlugin.GameData.NewData.SpeedLimiterOn", "DataCorePlugin.GameData.SpeedLimiterOn", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("2f", "vehicle.damage.aero", "DataCorePlugin.GameData.NewData.AeroDamage", "DataCorePlugin.GameData.AeroDamage", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("2g", "vehicle.damage.suspension", "DataCorePlugin.GameData.NewData.SuspensionDamage", "DataCorePlugin.GameData.SuspensionDamage", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("2h", "vehicle.damage.transmission", "DataCorePlugin.GameData.NewData.TransmissionDamage", "DataCorePlugin.GameData.TransmissionDamage", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("2i", "session.flag.current", "DataCorePlugin.GameData.NewData.Flag_Name", "DataCorePlugin.GameData.Flag_Name", FieldComputation.None, FieldConversion.Text, null, 1.0, "NONE", FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2j", "session.flag.green", "DataCorePlugin.GameData.NewData.Flag_Green", "DataCorePlugin.GameData.Flag_Green", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2k", "session.flag.yellow", "DataCorePlugin.GameData.NewData.Flag_Yellow", "DataCorePlugin.GameData.Flag_Yellow", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2l", "session.flag.blue", "DataCorePlugin.GameData.NewData.Flag_Blue", "DataCorePlugin.GameData.Flag_Blue", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2m", "session.flag.white", "DataCorePlugin.GameData.NewData.Flag_White", "DataCorePlugin.GameData.Flag_White", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2n", "session.flag.red", "DataCorePlugin.GameData.NewData.Flag_Red", "DataCorePlugin.GameData.Flag_Red", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2o", "session.flag.black", "DataCorePlugin.GameData.NewData.Flag_Black", "DataCorePlugin.GameData.Flag_Black", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2p", "session.flag.checkered", "DataCorePlugin.GameData.NewData.Flag_Checkered", "DataCorePlugin.GameData.Flag_Checkered", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2q", "session.flag.black_white", "DataCorePlugin.GameData.NewData.Flag_BlackWhite", "DataCorePlugin.GameData.Flag_BlackWhite", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2r", "session.flag.black_orange", "DataCorePlugin.GameData.NewData.Flag_BlackOrange", "DataCorePlugin.GameData.Flag_BlackOrange", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2s", "session.local_yellow", "DataCorePlugin.GameData.NewData.LocalYellow", "DataCorePlugin.GameData.LocalYellow", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2t", "session.safety_car", "DataCorePlugin.GameData.NewData.SafetyCarActive", "DataCorePlugin.GameData.SafetyCarActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2u", "session.virtual_safety_car", "DataCorePlugin.GameData.NewData.VirtualSafetyCarActive", "DataCorePlugin.GameData.VirtualSafetyCarActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2v", "session.penalty.active", "DataCorePlugin.GameData.NewData.PenaltyActive", "DataCorePlugin.GameData.PenaltyActive", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("2w", "session.penalty.type", "DataCorePlugin.GameData.NewData.PenaltyType", "DataCorePlugin.GameData.PenaltyType", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("2x", "session.penalty.time", "DataCorePlugin.GameData.NewData.PenaltyTime", "DataCorePlugin.GameData.PenaltyTime", FieldComputation.None, FieldConversion.Number, "0", 1000.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("2y", "session.penalty.message", "DataCorePlugin.GameData.NewData.PenaltyMessage", "DataCorePlugin.GameData.PenaltyMessage", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("2z", "track.name", "DataCorePlugin.GameData.NewData.TrackName", "DataCorePlugin.GameData.TrackName", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("30", "track.configuration", "DataCorePlugin.GameData.NewData.TrackConfig", "DataCorePlugin.GameData.TrackConfig", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("31", "track.length", "DataCorePlugin.GameData.NewData.TrackLength", "DataCorePlugin.GameData.TrackLength", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("32", "track.temperature", "DataCorePlugin.GameData.NewData.RoadTemperature", "DataCorePlugin.GameData.RoadTemperature", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("33", "track.wetness", "DataCorePlugin.GameData.NewData.TrackWetness", "DataCorePlugin.GameData.TrackWetness", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("34", "environment.air_temperature", "DataCorePlugin.GameData.NewData.AirTemperature", "DataCorePlugin.GameData.AirTemperature", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("35", "environment.rain_level", "DataCorePlugin.GameData.NewData.RainIntensity", "DataCorePlugin.GameData.RainIntensity", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("36", "environment.wind_speed", "DataCorePlugin.GameData.NewData.WindSpeed", "DataCorePlugin.GameData.WindSpeed", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("37", "environment.wind_direction", "DataCorePlugin.GameData.NewData.WindDirection", "DataCorePlugin.GameData.WindDirection", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("38", "environment.time_of_day", "DataCorePlugin.GameData.NewData.TimeOfDay", "DataCorePlugin.GameData.TimeOfDay", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("39", "environment.cloud_level", "DataCorePlugin.GameData.NewData.CloudLevel", "DataCorePlugin.GameData.CloudLevel", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3a", "environment.forecast", "DataCorePlugin.GameData.NewData.WeatherForecast", "DataCorePlugin.GameData.WeatherForecast", FieldComputation.None, FieldConversion.Text, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("3b", "motion.acceleration_longitudinal", "DataCorePlugin.GameData.NewData.AccelerationSurge", "DataCorePlugin.GameData.AccelerationSurge", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3c", "motion.acceleration_lateral", "DataCorePlugin.GameData.NewData.AccelerationSway", "DataCorePlugin.GameData.AccelerationSway", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3d", "motion.acceleration_vertical", "DataCorePlugin.GameData.NewData.AccelerationHeave", "DataCorePlugin.GameData.AccelerationHeave", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3e", "motion.g_force_longitudinal", null, null, FieldComputation.GForceLongitudinal, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3f", "motion.g_force_lateral", null, null, FieldComputation.GForceLateral, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3g", "motion.g_force_vertical", null, null, FieldComputation.GForceVertical, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3h", "motion.pitch", "DataCorePlugin.GameData.NewData.OrientationPitch", "DataCorePlugin.GameData.OrientationPitch", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3i", "motion.roll", "DataCorePlugin.GameData.NewData.OrientationRoll", "DataCorePlugin.GameData.OrientationRoll", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3j", "motion.yaw", "DataCorePlugin.GameData.NewData.OrientationYaw", "DataCorePlugin.GameData.OrientationYaw", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3k", "motion.slip_angle", null, null, FieldComputation.SlipAngle, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3l", "motion.ffb_force", "DataCorePlugin.GameData.NewData.ForceFeedback", "DataCorePlugin.GameData.ForceFeedback", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("3m", "tyre.front_left.pressure", "DataCorePlugin.GameData.NewData.TyrePressureFrontLeft", "DataCorePlugin.GameData.TyrePressureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3n", "tyre.front_right.pressure", "DataCorePlugin.GameData.NewData.TyrePressureFrontRight", "DataCorePlugin.GameData.TyrePressureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3o", "tyre.rear_left.pressure", "DataCorePlugin.GameData.NewData.TyrePressureRearLeft", "DataCorePlugin.GameData.TyrePressureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3p", "tyre.rear_right.pressure", "DataCorePlugin.GameData.NewData.TyrePressureRearRight", "DataCorePlugin.GameData.TyrePressureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3q", "tyre.front_left.temperature", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontLeft", "DataCorePlugin.GameData.TyreTemperatureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3r", "tyre.front_right.temperature", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontRight", "DataCorePlugin.GameData.TyreTemperatureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3s", "tyre.rear_left.temperature", "DataCorePlugin.GameData.NewData.TyreTemperatureRearLeft", "DataCorePlugin.GameData.TyreTemperatureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3t", "tyre.rear_right.temperature", "DataCorePlugin.GameData.NewData.TyreTemperatureRearRight", "DataCorePlugin.GameData.TyreTemperatureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3u", "tyre.front_left.temperature_inner", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontLeftInner", "DataCorePlugin.GameData.TyreTemperatureFrontLeftInner", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3v", "tyre.front_right.temperature_inner", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontRightInner", "DataCorePlugin.GameData.TyreTemperatureFrontRightInner", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3w", "tyre.rear_left.temperature_inner", "DataCorePlugin.GameData.NewData.TyreTemperatureRearLeftInner", "DataCorePlugin.GameData.TyreTemperatureRearLeftInner", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3x", "tyre.rear_right.temperature_inner", "DataCorePlugin.GameData.NewData.TyreTemperatureRearRightInner", "DataCorePlugin.GameData.TyreTemperatureRearRightInner", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3y", "tyre.front_left.temperature_middle", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontLeftMiddle", "DataCorePlugin.GameData.TyreTemperatureFrontLeftMiddle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("3z", "tyre.front_right.temperature_middle", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontRightMiddle", "DataCorePlugin.GameData.TyreTemperatureFrontRightMiddle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("40", "tyre.rear_left.temperature_middle", "DataCorePlugin.GameData.NewData.TyreTemperatureRearLeftMiddle", "DataCorePlugin.GameData.TyreTemperatureRearLeftMiddle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("41", "tyre.rear_right.temperature_middle", "DataCorePlugin.GameData.NewData.TyreTemperatureRearRightMiddle", "DataCorePlugin.GameData.TyreTemperatureRearRightMiddle", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("42", "tyre.front_left.temperature_outer", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontLeftOuter", "DataCorePlugin.GameData.TyreTemperatureFrontLeftOuter", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("43", "tyre.front_right.temperature_outer", "DataCorePlugin.GameData.NewData.TyreTemperatureFrontRightOuter", "DataCorePlugin.GameData.TyreTemperatureFrontRightOuter", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("44", "tyre.rear_left.temperature_outer", "DataCorePlugin.GameData.NewData.TyreTemperatureRearLeftOuter", "DataCorePlugin.GameData.TyreTemperatureRearLeftOuter", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("45", "tyre.rear_right.temperature_outer", "DataCorePlugin.GameData.NewData.TyreTemperatureRearRightOuter", "DataCorePlugin.GameData.TyreTemperatureRearRightOuter", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("46", "tyre.front_left.carcass_temperature", "DataCorePlugin.GameData.NewData.TyreCarcassTemperatureFrontLeft", "DataCorePlugin.GameData.TyreCarcassTemperatureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("47", "tyre.front_right.carcass_temperature", "DataCorePlugin.GameData.NewData.TyreCarcassTemperatureFrontRight", "DataCorePlugin.GameData.TyreCarcassTemperatureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("48", "tyre.rear_left.carcass_temperature", "DataCorePlugin.GameData.NewData.TyreCarcassTemperatureRearLeft", "DataCorePlugin.GameData.TyreCarcassTemperatureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("49", "tyre.rear_right.carcass_temperature", "DataCorePlugin.GameData.NewData.TyreCarcassTemperatureRearRight", "DataCorePlugin.GameData.TyreCarcassTemperatureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4a", "tyre.front_left.surface_temperature", "DataCorePlugin.GameData.NewData.TyreSurfaceTemperatureFrontLeft", "DataCorePlugin.GameData.TyreSurfaceTemperatureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4b", "tyre.front_right.surface_temperature", "DataCorePlugin.GameData.NewData.TyreSurfaceTemperatureFrontRight", "DataCorePlugin.GameData.TyreSurfaceTemperatureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4c", "tyre.rear_left.surface_temperature", "DataCorePlugin.GameData.NewData.TyreSurfaceTemperatureRearLeft", "DataCorePlugin.GameData.TyreSurfaceTemperatureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4d", "tyre.rear_right.surface_temperature", "DataCorePlugin.GameData.NewData.TyreSurfaceTemperatureRearRight", "DataCorePlugin.GameData.TyreSurfaceTemperatureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4e", "tyre.front_left.wear", "DataCorePlugin.GameData.NewData.TyreWearFrontLeft", "DataCorePlugin.GameData.TyreWearFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4f", "tyre.front_right.wear", "DataCorePlugin.GameData.NewData.TyreWearFrontRight", "DataCorePlugin.GameData.TyreWearFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4g", "tyre.rear_left.wear", "DataCorePlugin.GameData.NewData.TyreWearRearLeft", "DataCorePlugin.GameData.TyreWearRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4h", "tyre.rear_right.wear", "DataCorePlugin.GameData.NewData.TyreWearRearRight", "DataCorePlugin.GameData.TyreWearRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("4i", "tyre.front_left.detached", "DataCorePlugin.GameData.NewData.WheelDetachedFrontLeft", "DataCorePlugin.GameData.WheelDetachedFrontLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("4j", "tyre.front_right.detached", "DataCorePlugin.GameData.NewData.WheelDetachedFrontRight", "DataCorePlugin.GameData.WheelDetachedFrontRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("4k", "tyre.rear_left.detached", "DataCorePlugin.GameData.NewData.WheelDetachedRearLeft", "DataCorePlugin.GameData.WheelDetachedRearLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("4l", "tyre.rear_right.detached", "DataCorePlugin.GameData.NewData.WheelDetachedRearRight", "DataCorePlugin.GameData.WheelDetachedRearRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Changes),
            new TelemetryField("4m", "tyre.front_left.punctured", "DataCorePlugin.GameData.NewData.TyrePuncturedFrontLeft", "DataCorePlugin.GameData.TyrePuncturedFrontLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4n", "tyre.front_right.punctured", "DataCorePlugin.GameData.NewData.TyrePuncturedFrontRight", "DataCorePlugin.GameData.TyrePuncturedFrontRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4o", "tyre.rear_left.punctured", "DataCorePlugin.GameData.NewData.TyrePuncturedRearLeft", "DataCorePlugin.GameData.TyrePuncturedRearLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4p", "tyre.rear_right.punctured", "DataCorePlugin.GameData.NewData.TyrePuncturedRearRight", "DataCorePlugin.GameData.TyrePuncturedRearRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4q", "tyre.front_left.flat_spot", "DataCorePlugin.GameData.NewData.TyreFlatSpotFrontLeft", "DataCorePlugin.GameData.TyreFlatSpotFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4r", "tyre.front_right.flat_spot", "DataCorePlugin.GameData.NewData.TyreFlatSpotFrontRight", "DataCorePlugin.GameData.TyreFlatSpotFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4s", "tyre.rear_left.flat_spot", "DataCorePlugin.GameData.NewData.TyreFlatSpotRearLeft", "DataCorePlugin.GameData.TyreFlatSpotRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4t", "tyre.rear_right.flat_spot", "DataCorePlugin.GameData.NewData.TyreFlatSpotRearRight", "DataCorePlugin.GameData.TyreFlatSpotRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Normal),
            new TelemetryField("4u", "tyre.front_left.slip", "DataCorePlugin.GameData.NewData.WheelSlipFrontLeft", "DataCorePlugin.GameData.WheelSlipFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("4v", "tyre.front_right.slip", "DataCorePlugin.GameData.NewData.WheelSlipFrontRight", "DataCorePlugin.GameData.WheelSlipFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("4w", "tyre.rear_left.slip", "DataCorePlugin.GameData.NewData.WheelSlipRearLeft", "DataCorePlugin.GameData.WheelSlipRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("4x", "tyre.rear_right.slip", "DataCorePlugin.GameData.NewData.WheelSlipRearRight", "DataCorePlugin.GameData.WheelSlipRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("4y", "tyre.front_left.load", "DataCorePlugin.GameData.NewData.TyreLoadFrontLeft", "DataCorePlugin.GameData.TyreLoadFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("4z", "tyre.front_right.load", "DataCorePlugin.GameData.NewData.TyreLoadFrontRight", "DataCorePlugin.GameData.TyreLoadFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("50", "tyre.rear_left.load", "DataCorePlugin.GameData.NewData.TyreLoadRearLeft", "DataCorePlugin.GameData.TyreLoadRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("51", "tyre.rear_right.load", "DataCorePlugin.GameData.NewData.TyreLoadRearRight", "DataCorePlugin.GameData.TyreLoadRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("52", "tyre.front_left.rotation_speed", "DataCorePlugin.GameData.NewData.WheelRotationSpeedFrontLeft", "DataCorePlugin.GameData.WheelRotationSpeedFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("53", "tyre.front_right.rotation_speed", "DataCorePlugin.GameData.NewData.WheelRotationSpeedFrontRight", "DataCorePlugin.GameData.WheelRotationSpeedFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("54", "tyre.rear_left.rotation_speed", "DataCorePlugin.GameData.NewData.WheelRotationSpeedRearLeft", "DataCorePlugin.GameData.WheelRotationSpeedRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("55", "tyre.rear_right.rotation_speed", "DataCorePlugin.GameData.NewData.WheelRotationSpeedRearRight", "DataCorePlugin.GameData.WheelRotationSpeedRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("56", "brake.front_left.temperature", "DataCorePlugin.GameData.NewData.BrakeTemperatureFrontLeft", "DataCorePlugin.GameData.BrakeTemperatureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("57", "brake.front_right.temperature", "DataCorePlugin.GameData.NewData.BrakeTemperatureFrontRight", "DataCorePlugin.GameData.BrakeTemperatureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("58", "brake.rear_left.temperature", "DataCorePlugin.GameData.NewData.BrakeTemperatureRearLeft", "DataCorePlugin.GameData.BrakeTemperatureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("59", "brake.rear_right.temperature", "DataCorePlugin.GameData.NewData.BrakeTemperatureRearRight", "DataCorePlugin.GameData.BrakeTemperatureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5a", "brake.front_left.pressure", "DataCorePlugin.GameData.NewData.BrakePressureFrontLeft", "DataCorePlugin.GameData.BrakePressureFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5b", "brake.front_right.pressure", "DataCorePlugin.GameData.NewData.BrakePressureFrontRight", "DataCorePlugin.GameData.BrakePressureFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5c", "brake.rear_left.pressure", "DataCorePlugin.GameData.NewData.BrakePressureRearLeft", "DataCorePlugin.GameData.BrakePressureRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5d", "brake.rear_right.pressure", "DataCorePlugin.GameData.NewData.BrakePressureRearRight", "DataCorePlugin.GameData.BrakePressureRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5e", "brake.front_left.wear", "DataCorePlugin.GameData.NewData.BrakeWearFrontLeft", "DataCorePlugin.GameData.BrakeWearFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5f", "brake.front_right.wear", "DataCorePlugin.GameData.NewData.BrakeWearFrontRight", "DataCorePlugin.GameData.BrakeWearFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5g", "brake.rear_left.wear", "DataCorePlugin.GameData.NewData.BrakeWearRearLeft", "DataCorePlugin.GameData.BrakeWearRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5h", "brake.rear_right.wear", "DataCorePlugin.GameData.NewData.BrakeWearRearRight", "DataCorePlugin.GameData.BrakeWearRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5i", "brake.front_left.abs_active", "DataCorePlugin.GameData.NewData.ABSActiveFrontLeft", "DataCorePlugin.GameData.ABSActiveFrontLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5j", "brake.front_right.abs_active", "DataCorePlugin.GameData.NewData.ABSActiveFrontRight", "DataCorePlugin.GameData.ABSActiveFrontRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5k", "brake.rear_left.abs_active", "DataCorePlugin.GameData.NewData.ABSActiveRearLeft", "DataCorePlugin.GameData.ABSActiveRearLeft", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5l", "brake.rear_right.abs_active", "DataCorePlugin.GameData.NewData.ABSActiveRearRight", "DataCorePlugin.GameData.ABSActiveRearRight", FieldComputation.None, FieldConversion.Boolean, null, 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5m", "suspension.front_left.travel", "DataCorePlugin.GameData.NewData.SuspensionTravelFrontLeft", "DataCorePlugin.GameData.SuspensionTravelFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5n", "suspension.front_right.travel", "DataCorePlugin.GameData.NewData.SuspensionTravelFrontRight", "DataCorePlugin.GameData.SuspensionTravelFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5o", "suspension.rear_left.travel", "DataCorePlugin.GameData.NewData.SuspensionTravelRearLeft", "DataCorePlugin.GameData.SuspensionTravelRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5p", "suspension.rear_right.travel", "DataCorePlugin.GameData.NewData.SuspensionTravelRearRight", "DataCorePlugin.GameData.SuspensionTravelRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5q", "suspension.front_left.velocity", "DataCorePlugin.GameData.NewData.SuspensionVelocityFrontLeft", "DataCorePlugin.GameData.SuspensionVelocityFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5r", "suspension.front_right.velocity", "DataCorePlugin.GameData.NewData.SuspensionVelocityFrontRight", "DataCorePlugin.GameData.SuspensionVelocityFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5s", "suspension.rear_left.velocity", "DataCorePlugin.GameData.NewData.SuspensionVelocityRearLeft", "DataCorePlugin.GameData.SuspensionVelocityRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5t", "suspension.rear_right.velocity", "DataCorePlugin.GameData.NewData.SuspensionVelocityRearRight", "DataCorePlugin.GameData.SuspensionVelocityRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Fast),
            new TelemetryField("5u", "suspension.front_left.damage", "DataCorePlugin.GameData.NewData.SuspensionDamageFrontLeft", "DataCorePlugin.GameData.SuspensionDamageFrontLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5v", "suspension.front_right.damage", "DataCorePlugin.GameData.NewData.SuspensionDamageFrontRight", "DataCorePlugin.GameData.SuspensionDamageFrontRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5w", "suspension.rear_left.damage", "DataCorePlugin.GameData.NewData.SuspensionDamageRearLeft", "DataCorePlugin.GameData.SuspensionDamageRearLeft", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
            new TelemetryField("5x", "suspension.rear_right.damage", "DataCorePlugin.GameData.NewData.SuspensionDamageRearRight", "DataCorePlugin.GameData.SuspensionDamageRearRight", FieldComputation.None, FieldConversion.Number, "0.###", 1.0, null, FieldComparison.None, 0.0, FieldRate.Slow),
        };
    }
}
