// Generated by tools/generate_configuration_schema.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

#include "application_configuration_generated.hpp"

namespace simcore::configuration {

enum class ValidationError : std::uint8_t {
  none,
  malformed,
  unsupported_schema,
  invalid_board,
  board_mismatch,
  invalid_hardware,
  invalid_transport,
  invalid_uart,
  invalid_module,
  invalid_screen,
  invalid_dashboard,
  invalid_widget,
  unknown_property,
  duplicate_property,
};

inline constexpr std::array<std::string_view, 14> kValidationErrorNames{{
    "none",
    "malformed",
    "unsupported_schema",
    "invalid_board",
    "board_mismatch",
    "invalid_hardware",
    "invalid_transport",
    "invalid_uart",
    "invalid_module",
    "invalid_screen",
    "invalid_dashboard",
    "invalid_widget",
    "unknown_property",
    "duplicate_property",
}};

[[nodiscard]] inline std::string_view validation_error_name(const ValidationError error) {
  const auto index = static_cast<std::size_t>(error);
  return index < kValidationErrorNames.size() ? kValidationErrorNames[index]
                                             : std::string_view{};
}

// A rejection plus enough context for the configurator to point at the
// offending place. Indices are -1 when the failure is not inside a widget.
struct ValidationFailure {
  ValidationError error{ValidationError::none};
  std::int16_t screen_index{-1};
  std::int16_t widget_index{-1};
  std::array<char, kValidationPathCapacity> path{};

  [[nodiscard]] constexpr bool ok() const {
    return error == ValidationError::none;
  }
};

namespace schema {

// Accepted property names per object. A name absent from the matching list
// is rejected as unknown_property; a repeated name is rejected as
// duplicate_property.

inline constexpr std::array<std::string_view, 2> kFontSpecKeys{{
    "family",
    "size_px",
}};

inline constexpr std::array<std::string_view, 1> kTimeTransformConfigKeys{{
    "format",
}};

inline constexpr std::array<std::string_view, 3> kNumberTransformConfigKeys{{
    "decimals",
    "scale",
    "offset",
}};

inline constexpr std::array<std::string_view, 1> kBoardConfigurationKeys{{
    "board",
}};

inline constexpr std::array<std::string_view, 5> kUartTelemetryConfigurationKeys{{
    "port",
    "tx_pin",
    "rx_pin",
    "baud_rate",
    "silence_esp_logs",
}};

inline constexpr std::array<std::string_view, 2> kTelemetryTransportConfigurationKeys{{
    "id",
    "uart",
}};

inline constexpr std::array<std::string_view, 3> kDeltaTimeScaleConfigurationKeys{{
    "enabled",
    "show_sign",
    "range_ms",
}};

inline constexpr std::array<std::string_view, 3> kDeltaTimeConfigurationKeys{{
    "unavailable_behavior",
    "placeholder",
    "scale",
}};

inline constexpr std::array<std::string_view, 4> kWidgetPlacementKeys{{
    "x",
    "y",
    "width",
    "height",
}};

inline constexpr std::array<std::string_view, 4> kWidgetInsetsKeys{{
    "left",
    "top",
    "right",
    "bottom",
}};

inline constexpr std::array<std::string_view, 3> kWidgetBorderKeys{{
    "color",
    "width_px",
    "radius_px",
}};

inline constexpr std::array<std::string_view, 4> kWidgetTitleStyleKeys{{
    "text",
    "font",
    "color",
    "offset_y_px",
}};

inline constexpr std::array<std::string_view, 4> kWidgetValueStyleKeys{{
    "font",
    "color",
    "alignment",
    "unavailable_text",
}};

inline constexpr std::array<std::string_view, 7> kValueTransformKeys{{
    "type",
    "format",
    "decimals",
    "scale",
    "offset",
    "prefix",
    "suffix",
}};

inline constexpr std::array<std::string_view, 1> kValueModifierKeys{{
    "type",
}};

inline constexpr std::array<std::string_view, 3> kDeltaTimeScaleStyleKeys{{
    "vertical_padding_px",
    "border_width_px",
    "border_radius_px",
}};

inline constexpr std::array<std::string_view, 9> kDeltaTimeWidgetConfigurationKeys{{
    "type",
    "id",
    "font",
    "placement",
    "z_index",
    "faster_color",
    "slower_color",
    "neutral_color",
    "scale",
}};

inline constexpr std::array<std::string_view, 2> kValueSourceConfigurationKeys{{
    "binding",
    "modifiers",
}};

inline constexpr std::array<std::string_view, 8> kWidgetConditionKeys{{
    "op",
    "value",
    "color",
    "background_color",
    "border_color",
    "hidden",
    "blink_ms",
    "hold_ms",
}};

inline constexpr std::array<std::string_view, 3> kTextSourceConfigurationKeys{{
    "binding",
    "modifiers",
    "transform",
}};

inline constexpr std::array<std::string_view, 10> kWidgetFrameKeys{{
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_inset_px",
    "condition_source",
    "conditions",
}};

inline constexpr std::array<std::string_view, 13> kTextWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_inset_px",
    "condition_source",
    "conditions",
    "sources",
    "value",
}};

inline constexpr std::array<std::string_view, 2> kValueRangeKeys{{
    "minimum",
    "maximum",
}};

inline constexpr std::array<std::string_view, 17> kBarWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_inset_px",
    "condition_source",
    "conditions",
    "source",
    "minimum",
    "maximum",
    "orientation",
    "inverted",
    "fill_color",
}};

inline constexpr std::array<std::string_view, 12> kShapeWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_inset_px",
    "condition_source",
    "conditions",
    "kind",
}};

inline constexpr std::array<std::string_view, 3> kScreenConfigurationKeys{{
    "id",
    "background_color",
    "widgets",
}};

inline constexpr std::array<std::string_view, 1> kDashboardConfigurationKeys{{
    "screens",
}};

inline constexpr std::array<std::string_view, 5> kApplicationConfigurationKeys{{
    "board",
    "hardware",
    "telemetry_transport",
    "delta_time",
    "dashboard",
}};

}  // namespace schema

}  // namespace simcore::configuration
