// Generated by tools/codegen/configuration_schema. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

#include "application_configuration_generated.hpp"

namespace pitrig::configuration {

enum class ValidationError : std::uint8_t {
  none,
  malformed,
  unsupported_schema,
  invalid_board,
  board_mismatch,
  invalid_hardware,
  invalid_led_pin,
  invalid_led_sprite,
  invalid_transport,
  invalid_uart,
  invalid_module,
  invalid_screen,
  invalid_dashboard,
  invalid_widget,
  invalid_slot,
  invalid_slot_page,
  unknown_property,
  duplicate_property,
};

inline constexpr std::array<std::string_view, 18> kValidationErrorNames{{
    "none",
    "malformed",
    "unsupported_schema",
    "invalid_board",
    "board_mismatch",
    "invalid_hardware",
    "invalid_led_pin",
    "invalid_led_sprite",
    "invalid_transport",
    "invalid_uart",
    "invalid_module",
    "invalid_screen",
    "invalid_dashboard",
    "invalid_widget",
    "invalid_slot",
    "invalid_slot_page",
    "unknown_property",
    "duplicate_property",
}};

[[nodiscard]] inline std::string_view validation_error_name(const ValidationError error) {
  const auto index = static_cast<std::size_t>(error);
  return index < kValidationErrorNames.size() ? kValidationErrorNames[index]
                                             : std::string_view{};
}

struct ValidationFailure {
  ValidationError error{ValidationError::none};
  std::int16_t screen_index{-1};
  std::int16_t widget_index{-1};
  std::array<char, kValidationPathCapacity> path{};

  [[nodiscard]] constexpr bool ok() const {
    return error == ValidationError::none;
  }
};

namespace schema {

inline constexpr std::array<std::string_view, 3> kFontSpecKeys{{
    "family",
    "size_px",
    "fallback",
}};

inline constexpr std::array<std::string_view, 1> kTimeTransformConfigKeys{{
    "format",
}};

inline constexpr std::array<std::string_view, 3> kNumberTransformConfigKeys{{
    "decimals",
    "scale",
    "offset",
}};

inline constexpr std::array<std::string_view, 1> kBoardConfigurationKeys{{
    "board",
}};

inline constexpr std::array<std::string_view, 1> kLedPaletteEntryKeys{{
    "color",
}};

inline constexpr std::array<std::string_view, 6> kLedSpriteConfigurationKeys{{
    "id",
    "width",
    "height",
    "frame_count",
    "palette",
    "pixels",
}};

inline constexpr std::array<std::string_view, 6> kLedColorRuleKeys{{
    "op",
    "value",
    "color",
    "background_color",
    "blink_ms",
    "hold_ms",
}};

inline constexpr std::array<std::string_view, 27> kLedEffectKeys{{
    "type",
    "id",
    "from",
    "count",
    "panel_mask",
    "source",
    "minimum",
    "maximum",
    "gate",
    "condition_source",
    "conditions",
    "hold_ms",
    "blink_ms",
    "mirrored",
    "inverted",
    "color",
    "background_color",
    "color_rules",
    "stops",
    "steps",
    "animation",
    "speed_ms",
    "sprite",
    "sprite_frame",
    "sprite_loop",
    "text",
    "font",
}};

inline constexpr std::array<std::string_view, 2> kLedSegmentConfigurationKeys{{
    "count",
    "direction",
}};

inline constexpr std::array<std::string_view, 16> kHardwareDeviceConfigurationKeys{{
    "type",
    "id",
    "pin",
    "chip",
    "brightness",
    "gamma",
    "current_limit_ma",
    "count",
    "segments",
    "width",
    "height",
    "order",
    "origin",
    "rotation_deg",
    "effects",
    "sprites",
}};

inline constexpr std::array<std::string_view, 5> kUartTelemetryConfigurationKeys{{
    "port",
    "tx_pin",
    "rx_pin",
    "baud_rate",
    "silence_esp_logs",
}};

inline constexpr std::array<std::string_view, 2> kTelemetryTransportConfigurationKeys{{
    "id",
    "uart",
}};

inline constexpr std::array<std::string_view, 4> kWidgetPlacementKeys{{
    "x",
    "y",
    "width",
    "height",
}};

inline constexpr std::array<std::string_view, 4> kWidgetInsetsKeys{{
    "left",
    "top",
    "right",
    "bottom",
}};

inline constexpr std::array<std::string_view, 3> kWidgetBorderKeys{{
    "color",
    "width_px",
    "radius_px",
}};

inline constexpr std::array<std::string_view, 4> kWidgetValueStyleKeys{{
    "font",
    "color",
    "alignment",
    "unavailable_text",
}};

inline constexpr std::array<std::string_view, 7> kValueTransformKeys{{
    "type",
    "format",
    "decimals",
    "scale",
    "offset",
    "prefix",
    "suffix",
}};

inline constexpr std::array<std::string_view, 1> kValueModifierKeys{{
    "type",
}};

inline constexpr std::array<std::string_view, 2> kValueSourceConfigurationKeys{{
    "binding",
    "modifiers",
}};

inline constexpr std::array<std::string_view, 9> kWidgetTitleStyleKeys{{
    "text",
    "source",
    "font",
    "color",
    "alignment",
    "offset_x_px",
    "offset_y_px",
    "border_gap",
    "gap_padding_px",
}};

inline constexpr std::array<std::string_view, 2> kColorStopKeys{{
    "at",
    "color",
}};

inline constexpr std::array<std::string_view, 2> kColorRampKeys{{
    "target",
    "stops",
}};

inline constexpr std::array<std::string_view, 2> kWidgetActionKeys{{
    "type",
    "screen",
}};

inline constexpr std::array<std::string_view, 8> kWidgetConditionKeys{{
    "op",
    "value",
    "color",
    "background_color",
    "border_color",
    "hidden",
    "blink_ms",
    "hold_ms",
}};

inline constexpr std::array<std::string_view, 2> kValueConditionKeys{{
    "op",
    "value",
}};

inline constexpr std::array<std::string_view, 3> kTextSourceConfigurationKeys{{
    "binding",
    "modifiers",
    "transform",
}};

inline constexpr std::array<std::string_view, 15> kWidgetFrameKeys{{
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
}};

inline constexpr std::array<std::string_view, 18> kTextWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "sources",
    "value",
}};

inline constexpr std::array<std::string_view, 2> kValueRangeKeys{{
    "minimum",
    "maximum",
}};

inline constexpr std::array<std::string_view, 25> kBarWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "source",
    "minimum",
    "maximum",
    "origin",
    "orientation",
    "inverted",
    "fill_color",
    "fill_grad_color",
    "fill_grad_mid_color",
}};

inline constexpr std::array<std::string_view, 32> kArcWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "source",
    "minimum",
    "maximum",
    "center_angle_deg",
    "sector_deg",
    "thickness_px",
    "radius_px",
    "x_offset_px",
    "y_offset_px",
    "centering",
    "track_color",
    "fill_color",
    "fill_grad_color",
    "fill_grad_mid_color",
    "mark",
    "inverted",
}};

inline constexpr std::array<std::string_view, 2> kIndicatorSegmentKeys{{
    "threshold",
    "color",
}};

inline constexpr std::array<std::string_view, 35> kIndicatorWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "source",
    "minimum",
    "maximum",
    "shape",
    "orientation",
    "center_angle_deg",
    "sector_deg",
    "thickness_px",
    "radius_px",
    "x_offset_px",
    "y_offset_px",
    "centering",
    "segment_gap_px",
    "segment_radius_px",
    "inverted",
    "off_color",
    "blink_threshold",
    "blink_ms",
    "segments",
}};

inline constexpr std::array<std::string_view, 4> kGraphTraceConfigurationKeys{{
    "source",
    "minimum",
    "maximum",
    "line_color",
}};

inline constexpr std::array<std::string_view, 24> kGraphWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "source",
    "minimum",
    "maximum",
    "point_count",
    "sample_interval_ms",
    "line_color",
    "line_width_px",
    "traces",
}};

inline constexpr std::array<std::string_view, 21> kImageWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "image",
    "sprite_frame",
    "sprite_frame_source",
    "recolor",
    "recolor_opa",
}};

inline constexpr std::array<std::string_view, 19> kShapeWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "kind",
    "clip_children",
    "widgets",
}};

inline constexpr std::array<std::string_view, 6> kSlotPageConfigurationKeys{{
    "in_loop",
    "trigger",
    "source",
    "duration_ms",
    "conditions",
    "widgets",
}};

inline constexpr std::array<std::string_view, 18> kSlotWidgetConfigurationKeys{{
    "type",
    "id",
    "placement",
    "z_index",
    "padding",
    "border",
    "title",
    "background_color",
    "background_grad_color",
    "background_grad_dir",
    "background_inset_px",
    "fill_corners",
    "action",
    "condition_source",
    "color_ramp",
    "conditions",
    "clip_children",
    "pages",
}};

inline constexpr std::array<std::string_view, 3> kScreenConfigurationKeys{{
    "id",
    "background_color",
    "widgets",
}};

inline constexpr std::array<std::string_view, 3> kDashboardConfigurationKeys{{
    "transition",
    "smoothing",
    "screens",
}};

inline constexpr std::array<std::string_view, 4> kApplicationConfigurationKeys{{
    "board",
    "hardware",
    "telemetry_transport",
    "dashboard",
}};

inline constexpr std::array<std::string_view, 2> kDashboardDocumentKeys{{
    "board",
    "dashboard",
}};

inline constexpr std::array<std::string_view, 2> kModulesDocumentKeys{{
    "board",
    "hardware",
}};

inline constexpr std::array<std::string_view, 2> kProtocolDocumentKeys{{
    "board",
    "telemetry_transport",
}};

[[nodiscard]] inline std::span<const std::string_view> document_keys(
    const ConfigurationDocument value) {
  switch (value) {
    case ConfigurationDocument::dashboard:
      return kDashboardDocumentKeys;
    case ConfigurationDocument::modules:
      return kModulesDocumentKeys;
    case ConfigurationDocument::protocol:
      return kProtocolDocumentKeys;
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const LedSpriteConfiguration& config) {
  if (config.width < 1 || config.width > kMaximumMatrixSide) {
    return "width";
  }
  if (config.height < 1 || config.height > kMaximumMatrixSide) {
    return "height";
  }
  if (config.frame_count < 1 || config.frame_count > kMaximumLedSpriteFrames) {
    return "frame_count";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const LedColorRule& config) {
  if (config.blink_ms != 0 &&
      (config.blink_ms < kMinimumBlinkMs || config.blink_ms > kMaximumBlinkMs)) {
    return "blink_ms";
  }
  if (config.hold_ms > kMaximumHoldMs) {
    return "hold_ms";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const LedEffect& config) {
  if (config.from > kMaximumLedsPerOutput) {
    return "from";
  }
  if (config.count != 0 &&
      (config.count < 1 || config.count > kMaximumLedsPerOutput)) {
    return "count";
  }
  if (config.hold_ms > kMaximumHoldMs) {
    return "hold_ms";
  }
  if (config.blink_ms != 0 &&
      (config.blink_ms < kMinimumBlinkMs || config.blink_ms > kMaximumBlinkMs)) {
    return "blink_ms";
  }
  if (config.speed_ms < 50 || config.speed_ms > 60000) {
    return "speed_ms";
  }
  if (config.sprite_frame > kMaximumLedSpriteFrames) {
    return "sprite_frame";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const LedSegmentConfiguration& config) {
  if (config.count < 1 || config.count > kMaximumLedsPerOutput) {
    return "count";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const HardwareDeviceConfiguration& config) {
  if (config.current_limit_ma != 0 &&
      (config.current_limit_ma < 100 || config.current_limit_ma > 20000)) {
    return "current_limit_ma";
  }
  if (config.count < 1 || config.count > kMaximumLedsPerOutput) {
    return "count";
  }
  if (config.width < 1 || config.width > kMaximumMatrixSide) {
    return "width";
  }
  if (config.height < 1 || config.height > kMaximumMatrixSide) {
    return "height";
  }
  if (config.rotation_deg > 270) {
    return "rotation_deg";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const UartTelemetryConfiguration& config) {
  if (config.baud_rate < 9600 || config.baud_rate > 2000000) {
    return "baud_rate";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const TelemetryTransportConfiguration& config) {
  if (config.uart.baud_rate < 9600 || config.uart.baud_rate > 2000000) {
    return "uart.baud_rate";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const WidgetBorder& config) {
  if (config.width_px > 240) {
    return "width_px";
  }
  if (config.radius_px > 480) {
    return "radius_px";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const WidgetTitleStyle& config) {
  if (config.gap_padding_px > 240) {
    return "gap_padding_px";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const WidgetCondition& config) {
  if (config.blink_ms != 0 &&
      (config.blink_ms < kMinimumBlinkMs || config.blink_ms > kMaximumBlinkMs)) {
    return "blink_ms";
  }
  if (config.hold_ms > kMaximumHoldMs) {
    return "hold_ms";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const WidgetFrame& config) {
  if (config.border.width_px > 240) {
    return "border.width_px";
  }
  if (config.border.radius_px > 480) {
    return "border.radius_px";
  }
  if (config.title.gap_padding_px > 240) {
    return "title.gap_padding_px";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const ArcWidgetConfiguration& config) {
  if (config.center_angle_deg > 359) {
    return "center_angle_deg";
  }
  if (config.sector_deg < 1 || config.sector_deg > 360) {
    return "sector_deg";
  }
  if (config.thickness_px < 1) {
    return "thickness_px";
  }
  if (config.radius_px != 0 &&
      (config.radius_px < 1 || config.radius_px > 2048)) {
    return "radius_px";
  }
  if (config.x_offset_px < -2048 || config.x_offset_px > 2048) {
    return "x_offset_px";
  }
  if (config.y_offset_px < -2048 || config.y_offset_px > 2048) {
    return "y_offset_px";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const IndicatorWidgetConfiguration& config) {
  if (config.center_angle_deg > 359) {
    return "center_angle_deg";
  }
  if (config.sector_deg < 1 || config.sector_deg > 360) {
    return "sector_deg";
  }
  if (config.thickness_px < 1) {
    return "thickness_px";
  }
  if (config.radius_px != 0 &&
      (config.radius_px < 1 || config.radius_px > 2048)) {
    return "radius_px";
  }
  if (config.x_offset_px < -2048 || config.x_offset_px > 2048) {
    return "x_offset_px";
  }
  if (config.y_offset_px < -2048 || config.y_offset_px > 2048) {
    return "y_offset_px";
  }
  if (config.blink_ms != 0 &&
      (config.blink_ms < kMinimumBlinkMs || config.blink_ms > kMaximumBlinkMs)) {
    return "blink_ms";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const GraphWidgetConfiguration& config) {
  if (config.point_count < 2 || config.point_count > kMaximumGraphPoints) {
    return "point_count";
  }
  if (config.sample_interval_ms < 1) {
    return "sample_interval_ms";
  }
  if (config.line_width_px < 1) {
    return "line_width_px";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const ImageWidgetConfiguration& config) {
  if (config.sprite_frame > kMaximumSpriteFrames) {
    return "sprite_frame";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const SlotPageConfiguration& config) {
  if (config.duration_ms > kMaximumHoldMs) {
    return "duration_ms";
  }
  return {};
}

[[nodiscard]] inline std::string_view range_error(const ApplicationConfiguration& config) {
  if (config.telemetry_transport.uart.baud_rate < 9600 || config.telemetry_transport.uart.baud_rate > 2000000) {
    return "telemetry_transport.uart.baud_rate";
  }
  return {};
}

}

}
