#!/usr/bin/env python3
"""Generate the bounded device configuration contract shared by firmware and configurator."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "configuration" / "configuration_schema.json"
OUTPUTS = {
    ROOT
    / "firmware/services/configuration_contract/include/application_configuration_generated.hpp": "cpp_contract",
    ROOT
    / "firmware/services/configuration/include/configuration_schema_generated.hpp": "cpp_parser",
    ROOT / "configurator/src/shared/configuration-schema.ts": "typescript",
    ROOT / "docs/configuration-schema.md": "markdown",
}

BANNER = "Generated by tools/generate_configuration_schema.py. Do not edit."

SCALAR_CPP = {
    "int": "int",
    "int16": "std::int16_t",
    "int32": "std::int32_t",
    "uint8": "std::uint8_t",
    "uint16": "std::uint16_t",
    "uint32": "std::uint32_t",
    "float": "float",
    "bool": "bool",
    "color": "std::uint32_t",
    "optional_color": "std::uint32_t",
}

SCALAR_TS = {
    "int": "number",
    "int16": "number",
    "int32": "number",
    "uint8": "number",
    "uint16": "number",
    "uint32": "number",
    "float": "number",
    "bool": "boolean",
    "color": "RgbColor",
    "optional_color": "RgbColor",
    "text": "string",
}

SCALAR_RANGES = {
    "int16": (-32768, 32767),
    "int32": (-2147483648, 2147483647),
    "uint8": (0, 255),
    "uint16": (0, 65535),
    "uint32": (0, 4294967295),
}

SCALAR_DOC = {
    "int": "integer",
    "int16": "integer, -32768..32767",
    "int32": "integer",
    "uint8": "integer, 0..255",
    "uint16": "integer, 0..65535",
    "uint32": "integer, 0 or greater",
    "float": "number",
    "bool": "boolean",
    "color": "string `#RRGGBB`",
    "optional_color": "string `#RRGGBB`",
    "text": "string",
}


def fail(message: str) -> None:
    print(f"configuration schema error: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_schema() -> dict[str, Any]:
    if not SOURCE.exists():
        fail(f"missing source document {SOURCE.relative_to(ROOT)}")
    try:
        document = json.loads(SOURCE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        fail(f"{SOURCE.relative_to(ROOT)} is not valid JSON: {error}")
    validate_schema(document)
    return document


def validate_schema(document: dict[str, Any]) -> None:
    for key in ("schema_version", "limits", "enums", "structs", "validation_errors"):
        if key not in document:
            fail(f"missing top-level key '{key}'")
    if not isinstance(document["schema_version"], int):
        fail("schema_version must be an integer")

    limits = document["limits"]
    structs = document["structs"]
    enums = document["enums"]
    externals = document.get("external_types", {})
    constants = document.get("constants", {})

    roots = [name for name, body in structs.items() if body.get("root")]
    if len(roots) != 1:
        fail(f"exactly one struct must be marked root, found {len(roots)}")

    known_scalars = set(SCALAR_CPP) | {"text"}
    for struct_name, body in structs.items():
        seen: set[str] = set()
        for field in body.get("fields", []):
            name = field.get("name")
            if not name:
                fail(f"{struct_name}: field without a name")
            if name in seen:
                fail(f"{struct_name}: duplicate field '{name}'")
            seen.add(name)
            kind = field.get("kind")
            if kind in known_scalars:
                continue
            if kind == "enum":
                if field.get("enum") not in enums:
                    fail(f"{struct_name}.{name}: unknown enum '{field.get('enum')}'")
            elif kind == "struct":
                if field.get("struct") not in structs:
                    fail(f"{struct_name}.{name}: unknown struct '{field.get('struct')}'")
            elif kind == "array":
                if field.get("struct") not in structs:
                    fail(f"{struct_name}.{name}: unknown struct '{field.get('struct')}'")
                if field.get("capacity") not in limits:
                    fail(f"{struct_name}.{name}: unknown capacity '{field.get('capacity')}'")
                if field.get("count_field") not in seen | {
                    other.get("name") for other in body.get("fields", [])
                }:
                    fail(f"{struct_name}.{name}: unknown count_field")
            elif kind == "external":
                if field.get("external") not in externals:
                    fail(f"{struct_name}.{name}: unknown external '{field.get('external')}'")
            else:
                fail(f"{struct_name}.{name}: unknown kind '{kind}'")
            if kind == "text" and field.get("capacity") not in limits:
                fail(f"{struct_name}.{name}: unknown capacity '{field.get('capacity')}'")

    for name, body in enums.items():
        values = body.get("json_values")
        if not values:
            fail(f"enum {name} has no values")
        if body.get("default") not in values:
            fail(f"enum {name}: default '{body.get('default')}' is not one of its values")

    for name, body in constants.items():
        if "value" not in body:
            fail(f"constant {name} has no value")


def root_struct(document: dict[str, Any]) -> str:
    return next(name for name, body in document["structs"].items() if body.get("root"))


def struct_order(document: dict[str, Any]) -> list[str]:
    """Dependency-first ordering so C++ definitions compile without forward declarations."""
    structs = document["structs"]
    ordered: list[str] = []
    visiting: set[str] = set()

    def visit(name: str) -> None:
        if name in ordered:
            return
        if name in visiting:
            fail(f"cyclic struct reference involving '{name}'")
        visiting.add(name)
        for field in structs[name].get("fields", []):
            if field["kind"] in ("struct", "array"):
                visit(field["struct"])
        visiting.discard(name)
        ordered.append(name)

    for name in structs:
        visit(name)
    return ordered


def serialized_fields(body: dict[str, Any]) -> list[dict[str, Any]]:
    return [field for field in body.get("fields", []) if field.get("serialized", True)]


def json_key(field: dict[str, Any]) -> str:
    return field.get("json", field["name"])


def object_keys(document: dict[str, Any], struct_name: str) -> list[str]:
    """Public JSON property names accepted inside one object, in declaration order."""
    body = document["structs"][struct_name]
    if body.get("serialized") is False:
        return []
    externals = document.get("external_types", {})
    # A widget variant carries the discriminator that selected it.
    keys: list[str] = ["type"] if body.get("widget_type") else []
    for field in serialized_fields(body):
        if field.get("flatten"):
            keys.extend(object_keys(document, field["struct"]))
        elif field["kind"] == "external" and field.get("inline"):
            # The external contributes its own keys inline; its C++ member name
            # is not a public property.
            keys.extend(externals[field["external"]]["keys"])
        else:
            keys.append(json_key(field))
    return keys


def text_fields(
    document: dict[str, Any], body: dict[str, Any]
) -> list[tuple[str, dict[str, Any]]]:
    """Bounded strings a validator sees at this level, following flattened structs.

    A flattened struct contributes its properties here, so its capacities have to
    be reported under this name too or a check would look them up and miss.
    """
    found: list[tuple[str, dict[str, Any]]] = []
    for field in serialized_fields(body):
        if field.get("flatten"):
            found.extend(text_fields(document, document["structs"][field["struct"]]))
        elif field["kind"] == "text":
            found.append((field["name"], field))
    return found


def child_types(document: dict[str, Any], body: dict[str, Any]) -> dict[str, str]:
    """Nested object type per public property, following flattened structs.

    A flattened struct contributes its properties at this level, so its children
    have to be reported here too or a validator walking the document would stop
    at the boundary and miss everything below it.
    """
    children: dict[str, str] = {}
    for field in serialized_fields(body):
        if field.get("flatten"):
            children.update(child_types(document, document["structs"][field["struct"]]))
        elif field["kind"] == "struct":
            children[json_key(field)] = field["struct"]
        elif field["kind"] == "array" and not field.get("json_variants"):
            children[json_key(field)] = field["struct"]
        elif field["kind"] == "external" and not field.get("inline"):
            children[json_key(field)] = field["external"]
    return children


def widget_variants(document: dict[str, Any]) -> dict[str, str]:
    """Widget discriminator value to the struct that carries its properties."""
    return {
        body["widget_type"]: name
        for name, body in document["structs"].items()
        if body.get("widget_type")
    }


def widget_pools(document: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """(discriminator, struct, storage array), in WidgetType order.

    The traits table is indexed by the enum, so the order has to be the enum's.
    Storage names are read from the schema rather than derived from the struct
    name, so renaming a pool cannot silently produce a table that compiles
    against the wrong array.
    """
    variants = widget_variants(document)
    declared = set(document["enums"]["WidgetType"]["json_values"])
    if set(variants) != declared:
        fail(
            "WidgetType values and widget_type structs disagree: "
            f"{sorted(declared ^ set(variants))}"
        )
    arrays = {
        field["struct"]: field
        for field in document["structs"]["DashboardConfiguration"]["fields"]
        if field["kind"] == "array"
    }
    pools: list[tuple[str, str, dict[str, Any]]] = []
    for value in document["enums"]["WidgetType"]["json_values"]:
        struct = variants[value]
        if struct not in arrays:
            fail(f"{struct} has no storage array in DashboardConfiguration")
        pools.append((value, struct, arrays[struct]))
    return pools


# --------------------------------------------------------------------------- C++


def cpp_text_default(value: str, capacity_name: str) -> str:
    if not value:
        return "{}"
    characters = ", ".join(f"'{character}'" for character in value)
    return "{" + characters + ", '\\0'}"


def cpp_default(field: dict[str, Any], document: dict[str, Any]) -> str:
    kind = field["kind"]
    if kind == "text":
        return cpp_text_default(field.get("default", ""), field["capacity"])
    if kind == "enum":
        enum_name = field["enum"]
        default = field.get("default", document["enums"][enum_name]["default"])
        return f"{{{enum_name}::{default}}}"
    if kind in ("color", "optional_color"):
        default = field.get("default")
        return "{}" if default is None else f"{{{default}}}"
    if kind == "bool":
        return "{true}" if field.get("default") else "{false}"
    if kind == "float":
        default = field.get("default", 0)
        # Suffixed so a braced initialiser takes a float rather than narrowing
        # a double constant.
        return "{}" if not default else f"{{{float(default)}F}}"
    if kind in SCALAR_CPP:
        default = field.get("default", 0)
        return "{}" if default in (0, None) else f"{{{default}}}"
    return "{}"


def cpp_field_type(field: dict[str, Any], document: dict[str, Any]) -> str:
    kind = field["kind"]
    if kind == "text":
        return f"std::array<char, {field['capacity']}>"
    if kind == "enum":
        return field["enum"]
    if kind == "struct":
        return field["struct"]
    if kind == "array":
        return f"std::array<{field['struct']}, {field['capacity']}>"
    if kind == "external":
        return document["external_types"][field["external"]]["cpp"]
    return SCALAR_CPP[kind]


def generate_cpp_contract(document: dict[str, Any]) -> str:
    lines = [
        f"// {BANNER}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <span>",
        "#include <string_view>",
        "",
    ]
    headers = sorted(
        {body["cpp_header"] for body in document.get("external_types", {}).values()}
    )
    lines.extend(f'#include "{header}"' for header in headers)
    lines.extend(["", "namespace simcore::configuration {", ""])

    lines.append(
        f"inline constexpr std::uint16_t kConfigurationSchemaVersion = "
        f"{document['schema_version']};"
    )
    lines.append("")
    for name, body in document.get("constants", {}).items():
        if body.get("doc"):
            lines.append(f"// {body['doc']}")
        lines.append(
            f"inline constexpr {body.get('cpp_type', 'std::uint32_t')} {name} = {body['value']}U;"
        )
    lines.append("")
    for name, body in document["limits"].items():
        if body.get("doc"):
            lines.append(f"// {body['doc']}")
        lines.append(f"inline constexpr std::size_t {name} = {body['value']};")
    lines.append("")

    for name, body in document["enums"].items():
        if body.get("doc"):
            lines.append(f"// {body['doc']}")
        lines.append(f"enum class {name} : std::uint8_t {{")
        lines.extend(f"  {value}," for value in body["json_values"])
        lines.append("};")
        lines.append("")

    for name in struct_order(document):
        body = document["structs"][name]
        if body.get("doc"):
            for chunk in wrap_comment(body["doc"]):
                lines.append(chunk)
        lines.append(f"struct {name} {{")
        for field in body.get("fields", []):
            field_type = cpp_field_type(field, document)
            lines.append(
                f"  {field_type} {field['name']}{cpp_default(field, document)};"
            )
        lines.append("};")
        lines.append("")

    lines.extend(
        [
            "// Wire spellings and their conversions. Both directions read the same",
            "// generated value list the parser allow-lists use, so a name cannot drift",
            "// between the contract, the parser, and the configurator.",
            "",
        ]
    )
    for name, body in document["enums"].items():
        values = body["json_values"]
        lines.append(
            f"inline constexpr std::array<std::string_view, {len(values)}> "
            f"k{name}Names{{{{"
        )
        lines.extend(f'    "{value}",' for value in values)
        lines.append("}};")
        lines.append("")
        lines.append(
            f"[[nodiscard]] inline std::string_view {snake(name)}_name(const {name} value) {{"
        )
        lines.append(
            f"  const auto index = static_cast<std::size_t>(value);"
        )
        lines.append(
            f"  return index < k{name}Names.size() ? k{name}Names[index] : std::string_view{{}};"
        )
        lines.append("}")
        lines.append("")
        lines.append(
            f"[[nodiscard]] inline bool {snake(name)}_from_name(const std::string_view name,"
        )
        lines.append(
            f"                                                  {name}& value) {{"
        )
        lines.append(f"  for (std::size_t index = 0; index < k{name}Names.size(); ++index) {{")
        lines.append(f"    if (k{name}Names[index] == name) {{")
        lines.append(f"      value = static_cast<{name}>(index);")
        lines.append("      return true;")
        lines.append("    }")
        lines.append("  }")
        lines.append("  return false;")
        lines.append("}")
        lines.append("")
    lines.extend(generate_cpp_widget_traits(document))
    lines.append("}  // namespace simcore::configuration")
    lines.append("")
    return "\n".join(lines)


def generate_cpp_widget_traits(document: dict[str, Any]) -> list[str]:
    """Per-type access to widget storage, so callers need not restate the list.

    Composing a dashboard, parsing a document, comparing two of them and warming
    the fonts a document needs all do the same thing for every widget type. Each
    of those used to spell the seven types out again; they walk this table
    instead, and a new widget type is added to the schema and nowhere else.
    """
    pools = widget_pools(document)
    lines = [
        "// Uniform access to the storage one widget type occupies in a document.",
        "// Anything that has to do the same thing for every type — composing,",
        "// parsing, comparing two documents, warming fonts — walks this table",
        "// rather than naming each type, so adding a widget type is a schema",
        "// change and not an edit in every such place.",
        "struct WidgetTypeTraits {",
        "  WidgetType type{};",
        "  std::string_view name{};",
        "  // The document property its pool is stored under, which is what a",
        "  // capacity rejection has to name.",
        "  std::string_view storage_key{};",
        "  // Instances of this type one document can hold.",
        "  std::size_t capacity{};",
        "  std::uint8_t (*count)(const DashboardConfiguration&){};",
        "  void (*set_count)(DashboardConfiguration&, std::uint8_t){};",
        "  // Null past the count, so a caller cannot reach an instance the",
        "  // document does not have.",
        "  const WidgetFrame* (*frame)(const DashboardConfiguration&,",
        "                              std::uint8_t){};",
        "  WidgetFrame* (*mutable_frame)(DashboardConfiguration&, std::uint8_t){};",
        "  // One instance as raw bytes, for the byte compare that decides whether",
        "  // a widget changed between two documents. Empty past the count, so two",
        "  // absent instances compare equal.",
        "  std::span<const std::byte> (*element_bytes)(const DashboardConfiguration&,",
        "                                              std::uint8_t){};",
        "};",
        "",
        f"inline constexpr std::array<WidgetTypeTraits, {len(pools)}> "
        "kWidgetTypeTraits{{",
    ]
    for value, struct, field in pools:
        pool = field["name"]
        count = field["count_field"]
        lines.extend(
            [
                "    {",
                f"        .type = WidgetType::{value},",
                f'        .name = "{value}",',
                f'        .storage_key = "{pool}",',
                f"        .capacity = {field['capacity']},",
                "        .count = [](const DashboardConfiguration& dashboard)",
                "            -> std::uint8_t { return dashboard." + count + "; },",
                "        .set_count = [](DashboardConfiguration& dashboard,",
                "                        const std::uint8_t value) {",
                f"          dashboard.{count} = value;",
                "        },",
                "        .frame = [](const DashboardConfiguration& dashboard,",
                "                    const std::uint8_t index) -> const WidgetFrame* {",
                f"          return index < dashboard.{count}",
                f"                     ? &dashboard.{pool}[index].frame",
                "                     : nullptr;",
                "        },",
                "        .mutable_frame = [](DashboardConfiguration& dashboard,",
                "                            const std::uint8_t index) -> WidgetFrame* {",
                f"          return index < dashboard.{count}",
                f"                     ? &dashboard.{pool}[index].frame",
                "                     : nullptr;",
                "        },",
                "        .element_bytes =",
                "            [](const DashboardConfiguration& dashboard,",
                "               const std::uint8_t index) -> std::span<const std::byte> {",
                f"          if (index >= dashboard.{count}) {{",
                "            return {};",
                "          }",
                f"          return std::as_bytes(std::span{{&dashboard.{pool}[index], 1}});",
                "        },",
                "    },",
            ]
        )
    lines.extend(
        [
            "}};",
            "",
            "// A WidgetType always comes from the parser or from a reference the",
            "// parser wrote, so it is always in range; the guard keeps a corrupted",
            "// value from indexing past the table rather than reporting an error no",
            "// caller could act on.",
            "[[nodiscard]] inline const WidgetTypeTraits& widget_traits(",
            "    const WidgetType type) {",
            "  const auto index = static_cast<std::size_t>(type);",
            "  return index < kWidgetTypeTraits.size() ? kWidgetTypeTraits[index]",
            "                                         : kWidgetTypeTraits[0];",
            "}",
            "",
        ]
    )
    return lines


def snake(name: str) -> str:
    result: list[str] = []
    for index, character in enumerate(name):
        if character.isupper() and index > 0:
            result.append("_")
        result.append(character.lower())
    return "".join(result)


def wrap_comment(text: str, width: int = 76) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = "//"
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = "//"
        current += f" {word}"
    if current != "//":
        lines.append(current)
    return lines


def generate_cpp_parser(document: dict[str, Any]) -> str:
    errors = document["validation_errors"]
    lines = [
        f"// {BANNER}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        '#include "application_configuration_generated.hpp"',
        "",
        "namespace simcore::configuration {",
        "",
        "enum class ValidationError : std::uint8_t {",
    ]
    lines.extend(f"  {entry['name']}," for entry in errors)
    lines.append("};")
    lines.append("")
    lines.append(
        f"inline constexpr std::array<std::string_view, {len(errors)}> "
        "kValidationErrorNames{{"
    )
    lines.extend(f'    "{entry["name"]}",' for entry in errors)
    lines.append("}};")
    lines.append("")
    lines.append(
        "[[nodiscard]] inline std::string_view validation_error_name("
        "const ValidationError error) {"
    )
    lines.append("  const auto index = static_cast<std::size_t>(error);")
    lines.append(
        "  return index < kValidationErrorNames.size() ? kValidationErrorNames[index]"
    )
    lines.append("                                             : std::string_view{};")
    lines.append("}")
    lines.append("")
    lines.extend(
        [
            "// A rejection plus enough context for the configurator to point at the",
            "// offending place. Indices are -1 when the failure is not inside a widget.",
            "struct ValidationFailure {",
            "  ValidationError error{ValidationError::none};",
            "  std::int16_t screen_index{-1};",
            "  std::int16_t widget_index{-1};",
            "  std::array<char, kValidationPathCapacity> path{};",
            "",
            "  [[nodiscard]] constexpr bool ok() const {",
            "    return error == ValidationError::none;",
            "  }",
            "};",
            "",
            "namespace schema {",
            "",
            "// Accepted property names per object. A name absent from the matching list",
            "// is rejected as unknown_property; a repeated name is rejected as",
            "// duplicate_property.",
            "",
        ]
    )
    key_sets = {
        name: body["keys"]
        for name, body in document.get("external_types", {}).items()
        if body.get("keys")
    }
    key_sets.update(
        {name: object_keys(document, name) for name in document["structs"]}
    )
    for name, keys in key_sets.items():
        if not keys:
            continue
        lines.append(
            f"inline constexpr std::array<std::string_view, {len(keys)}> k{name}Keys{{{{"
        )
        lines.extend(f'    "{key}",' for key in keys)
        lines.append("}};")
        lines.append("")
    lines.append("}  // namespace schema")
    lines.append("")
    lines.append("}  // namespace simcore::configuration")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------- TypeScript


def ts_field_type(field: dict[str, Any], document: dict[str, Any]) -> str:
    kind = field["kind"]
    if kind == "enum":
        return field["enum"]
    if kind == "struct":
        return field["struct"]
    if kind == "array":
        if field.get("json_variants"):
            return "WidgetConfiguration[]"
        return f"{field['struct']}[]"
    if kind == "external":
        return document["external_types"][field["external"]]["typescript"]
    return SCALAR_TS[kind]


def generate_typescript(document: dict[str, Any]) -> str:
    lines = [
        f"// {BANNER}",
        "",
        "export type RgbColor = `#${string}`",
        "",
        f"export const CONFIGURATION_SCHEMA_VERSION = {document['schema_version']}",
        "",
    ]
    for name, body in document["limits"].items():
        lines.append(f"/** {body.get('doc', '')} */")
        lines.append(f"export const {screaming(name)} = {body['value']}")
    lines.append("")

    for name, body in document["enums"].items():
        union = " | ".join(f"'{value}'" for value in body["json_values"])
        lines.append(f"/** {body.get('doc', '')} */")
        lines.append(f"export type {name} = {union}")
        lines.append(
            f"export const {screaming(name)}_VALUES: readonly {name}[] = "
            f"[{', '.join(chr(39) + value + chr(39) for value in body['json_values'])}]"
        )
        lines.append("")

    error_names = [entry["name"] for entry in document["validation_errors"]]
    lines.append(
        "/** Reason token a device puts after `@SC:ERR:` when it rejects a document. */"
    )
    lines.append(
        "export type ValidationErrorToken = "
        + " | ".join(f"'{name}'" for name in error_names)
    )
    lines.append(
        "export const VALIDATION_ERROR_TOKENS: readonly ValidationErrorToken[] = "
        f"[{', '.join(chr(39) + name + chr(39) for name in error_names)}]"
    )
    lines.append("")

    externals = document.get("external_types", {})
    if "FontSpec" in externals:
        lines.extend(
            [
                "export interface FontSpec {",
                "  family?: string",
                "  size_px?: number",
                "}",
                "",
            ]
        )
    if "TimeTransformConfig" in externals:
        lines.extend(
            [
                "export interface TimeTransform {",
                "  format?: 'duration_ms' | 'signed_duration_ms'",
                "}",
                "",
            ]
        )
    if "NumberTransformConfig" in externals:
        lines.extend(
            [
                "export interface NumberTransform {",
                "  decimals?: number",
                "  scale?: number",
                "  offset?: number",
                "}",
                "",
            ]
        )

    for name in struct_order(document):
        body = document["structs"][name]
        if body.get("serialized") is False:
            continue
        if body.get("json_kind") == "empty_array":
            if body.get("doc"):
                lines.append(f"/** {body['doc']} */")
            lines.append(f"export type {name} = readonly never[]")
            lines.append("")
            continue
        fields = serialized_fields(body)
        if not fields:
            continue
        if body.get("doc"):
            lines.append(f"/** {body['doc']} */")
        # An inline external contributes its properties at this level rather
        # than under its own key, so the interface extends it.
        inherited = [
            document["external_types"][field["external"]]["typescript"]
            for field in fields
            if field["kind"] == "external" and field.get("inline")
        ]
        extends = f" extends {', '.join(inherited)}" if inherited else ""
        lines.append(f"export interface {name}{extends} {{")
        if body.get("widget_type"):
            lines.append(f"  type: '{body['widget_type']}'")
        for field in fields:
            if field["kind"] == "external" and field.get("inline"):
                continue
            if field.get("flatten"):
                # The nested object contributes its properties at this level.
                for inner in serialized_fields(document["structs"][field["struct"]]):
                    inner_optional = "" if inner.get("required") else "?"
                    lines.append(
                        f"  {json_key(inner)}{inner_optional}: "
                        f"{ts_field_type(inner, document)}"
                    )
                continue
            optional = "" if field.get("required") else "?"
            lines.append(
                f"  {json_key(field)}{optional}: {ts_field_type(field, document)}"
            )
        lines.append("}")
        lines.append("")

    variants = widget_variants(document)
    if variants:
        union = " | ".join(sorted(variants.values()))
        lines.append(
            "/** Discriminated widget union. Adding a widget type adds one member here. */"
        )
        lines.append(f"export type WidgetConfiguration = {union}")
        lines.append("")
        rendered = ", ".join(f"'{value}'" for value in variants)
        lines.append(f"export const WIDGET_TYPES: readonly string[] = [{rendered}]")
        lines.append("")

    lines.extend(
        [
            "/** Property names accepted inside each object, mirroring the firmware allow-lists. */",
            "export const SCHEMA_OBJECT_KEYS: Record<string, readonly string[]> = {",
        ]
    )
    for name in document["structs"]:
        keys = object_keys(document, name)
        if not keys:
            continue
        rendered = ", ".join(f"'{key}'" for key in keys)
        lines.append(f"  {name}: [{rendered}],")
    lines.append("}")
    lines.append("")

    variants = widget_variants(document)
    rendered_variants = ", ".join(
        f"{key}: '{struct}'" for key, struct in variants.items()
    )
    lines.extend(
        [
            "/** Struct that carries each widget variant, keyed by its discriminator. */",
            "export const SCHEMA_WIDGET_STRUCTS: Record<string, string> = "
            f"{{ {rendered_variants} }}",
            "",
            "/**",
            " * Nested object type for each property, so a validator can walk an unknown",
            " * document without a hand-maintained mapping.",
            " */",
            "export const SCHEMA_CHILD_TYPES: Record<string, Record<string, string>> = {",
        ]
    )
    for name, body in document["structs"].items():
        if body.get("serialized") is False:
            continue
        children = child_types(document, body)
        if not children:
            continue
        rendered = ", ".join(f"{key}: '{value}'" for key, value in children.items())
        lines.append(f"  {name}: {{ {rendered} }},")
    lines.append("}")
    lines.append("")

    lines.extend(
        [
            "/** Bounded string capacities. Values include the terminator the firmware stores. */",
            "export const TEXT_CAPACITIES: Record<string, number> = {",
        ]
    )
    for struct_name in document["structs"]:
        for owner, field in text_fields(document, document["structs"][struct_name]):
            limit = document["limits"][field["capacity"]]["value"]
            lines.append(f"  '{struct_name}.{json_key(field)}': {limit},")
            del owner
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def screaming(name: str) -> str:
    trimmed = name[1:] if name.startswith("k") and name[1:2].isupper() else name
    return snake(trimmed).upper()


# ------------------------------------------------------------------------ Markdown


def generate_markdown(document: dict[str, Any]) -> str:
    version = document["schema_version"]
    lines = [
        "# Configuration schema reference",
        "",
        f"This file is generated from `configuration/configuration_schema.json`. "
        f"It is the mechanical property reference for configuration schema {version}. "
        "Narrative rules, presence semantics, and the control protocol live in "
        "[device-configuration.md](device-configuration.md).",
        "",
        f"Schema version: {version}.",
        "",
        "## Limits",
        "",
        "| Constant | Value | Meaning |",
        "| --- | --- | --- |",
    ]
    for name, body in document["limits"].items():
        lines.append(f"| `{name}` | {body['value']} | {body.get('doc', '')} |")
    lines.append("")

    lines.extend(["## Enumerations", "", "| Type | Accepted values | Meaning |", "| --- | --- | --- |"])
    for name, body in document["enums"].items():
        values = ", ".join(f"`{value}`" for value in body["json_values"])
        lines.append(f"| `{name}` | {values} | {body.get('doc', '')} |")
    lines.append("")

    lines.extend(["## Objects", ""])
    for name in document["structs"]:
        body = document["structs"][name]
        if body.get("serialized") is False:
            continue
        fields = [field for field in serialized_fields(body) if not field.get("flatten")]
        if not fields:
            continue
        flattened = [
            field["struct"]
            for field in serialized_fields(body)
            if field.get("flatten") and field["kind"] == "struct"
        ]
        lines.append(f"### {name}")
        lines.append("")
        if body.get("doc"):
            lines.append(body["doc"])
            lines.append("")
        if flattened:
            # A flattened struct's properties are plain properties of this object
            # on the wire, so a reader of this table has to be told where the
            # rest of them are listed.
            links = [f"[`{struct}`](#{struct.lower()})" for struct in flattened]
            references = (
                links[0] if len(links) == 1 else f"{', '.join(links[:-1])} and {links[-1]}"
            )
            lines.append(
                f"Also carries the properties of {references}, flattened: they are "
                "plain properties of this object in JSON."
            )
            lines.append("")
        lines.append("| Property | Type | Default |")
        lines.append("| --- | --- | --- |")
        if body.get("widget_type"):
            lines.append(
                f"| `type` | `WidgetType`, fixed `{body['widget_type']}` | required |"
            )
        for field in fields:
            if field["kind"] == "external" and field.get("inline"):
                external = document["external_types"][field["external"]]
                for key in external["keys"]:
                    lines.append(
                        f"| `{key}` | see `{field['external']}` | absent |"
                    )
                continue
            lines.append(
                f"| `{json_key(field)}` | {markdown_type(field, document)} | "
                f"{markdown_default(field, document)} |"
            )
        lines.append("")

    lines.extend(["## Validation errors", "", "| Token | Meaning |", "| --- | --- |"])
    for entry in document["validation_errors"]:
        lines.append(f"| `{entry['name']}` | {entry.get('doc', '')} |")
    lines.append("")
    return "\n".join(lines)


def markdown_type(field: dict[str, Any], document: dict[str, Any]) -> str:
    kind = field["kind"]
    if kind == "enum":
        return f"`{field['enum']}`"
    if kind == "struct":
        return f"[`{field['struct']}`](#{field['struct'].lower()})"
    if kind == "array":
        capacity = document["limits"][field["capacity"]]["value"]
        variants = field.get("json_variants")
        if variants:
            rendered = ", ".join(
                f"[`{struct}`](#{struct.lower()})" for struct in variants.values()
            )
            return f"array of {rendered}, max {capacity}, discriminated by `type`"
        return f"array of [`{field['struct']}`](#{field['struct'].lower()}), max {capacity}"
    if kind == "external":
        return f"`{field['external']}`"
    if kind == "text":
        capacity = document["limits"][field["capacity"]]["value"]
        return f"string, max {capacity - 1} bytes"
    return SCALAR_DOC.get(kind, kind)


def markdown_default(field: dict[str, Any], document: dict[str, Any]) -> str:
    kind = field["kind"]
    if kind == "enum":
        default = field.get("default", document["enums"][field["enum"]]["default"])
        return f"`{default}`"
    if kind in ("color", "optional_color"):
        default = field.get("default")
        if default is None:
            return "absent"
        if str(default).startswith("k"):
            return f"`{default}` (no background)"
        return f"`#{int(str(default), 16):06X}`"
    if kind == "text":
        default = field.get("default", "")
        return f"`{default}`" if default else "empty"
    if kind == "bool":
        return "`true`" if field.get("default") else "`false`"
    if kind in ("struct", "array", "external"):
        return "absent"
    return f"`{field.get('default', 0)}`"


# ----------------------------------------------------------------------- Pipeline


def expected_outputs(document: dict[str, Any]) -> dict[Path, str]:
    generators = {
        "cpp_contract": generate_cpp_contract,
        "cpp_parser": generate_cpp_parser,
        "typescript": generate_typescript,
        "markdown": generate_markdown,
    }
    return {path: generators[kind](document) for path, kind in OUTPUTS.items()}


def write_or_check(outputs: dict[Path, str], check: bool) -> None:
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        fail("generated configuration schema files are stale: " + ", ".join(map(str, stale)))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = load_schema()
    write_or_check(expected_outputs(document), args.check)
    structs = len(document["structs"])
    enums = len(document["enums"])
    print(
        f"configuration schema: version {document['schema_version']}, "
        f"{structs} objects, {enums} enumerations"
    )


if __name__ == "__main__":
    main()
