// Generated by tools/generate_configuration_schema.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

#include "font_asset_types.hpp"
#include "number_transform.hpp"
#include "time_transform.hpp"

namespace simcore::configuration {

inline constexpr std::uint16_t kConfigurationSchemaVersion = 8;

// Sentinel meaning no background is painted. Not representable in JSON; omit the property instead.
inline constexpr std::uint32_t kTransparentColor = 0xFFFFFFFFU;

// Maximum compact JSON payload in bytes, for both the wire and NVS. Sized so a screen filled to every per-type cap still fits with room to spare; the buffers it sizes and the parser's document both live in external memory.
inline constexpr std::size_t kMaximumPayloadSize = 65536;
// Dashboard screens the driver swipes between. Widget storage is a dashboard-wide pool, so a screen costs only its reference table; what bounds the count is how many screens are reachable mid-corner rather than RAM.
inline constexpr std::size_t kMaximumScreens = 4;
// Ordered widget references per screen. Exactly the sum of every per-type cap below, so one screen can hold the whole pool; what bounds the widgets across every screen is the pool itself, and what bounds a document is kMaximumPayloadSize.
inline constexpr std::size_t kMaximumWidgetsPerScreen = 94;
// Widget groups per screen. A group is one LVGL container, so it costs its own reference table rather than widget storage.
inline constexpr std::size_t kMaximumGroups = 8;
// Ordered widget references inside one group. A group is an area of a screen rather than a screen, so it needs far fewer than a screen does.
inline constexpr std::size_t kMaximumWidgetsPerGroup = 16;
// Tap targets for the whole dashboard. An action makes one object clickable and costs one binding; the bound keeps that a decision about memory rather than an open list.
inline constexpr std::size_t kMaximumActions = 16;
// Slots for the whole dashboard. A slot is a box whose groups are mutually exclusive; slot numbers run 1..kMaximumSlots and 0 means a group is not in one.
inline constexpr std::size_t kMaximumSlots = 4;
// Text widget storage for the whole dashboard. A dense dashboard spends most of its widgets here: a tyre quadrant alone is eight readouts.
inline constexpr std::size_t kMaximumTextWidgets = 32;
// Shape widget storage for the whole dashboard. Shapes carry a dashboard's layout, so this is the most generous cap.
inline constexpr std::size_t kMaximumShapeWidgets = 24;
// Bar widget storage for the whole dashboard.
inline constexpr std::size_t kMaximumBarWidgets = 16;
// Arc widget storage for the whole dashboard.
inline constexpr std::size_t kMaximumArcWidgets = 8;
// Indicator strip storage for the whole dashboard.
inline constexpr std::size_t kMaximumIndicatorWidgets = 4;
// Graph storage for the whole dashboard. Each instance owns a sample ring buffer, which is why this cap is the smallest.
inline constexpr std::size_t kMaximumGraphWidgets = 2;
// Image widget storage for the whole dashboard.
inline constexpr std::size_t kMaximumImageWidgets = 8;
// Segments in one indicator strip.
inline constexpr std::size_t kMaximumIndicatorSegments = 16;
// Samples one graph retains. The ring buffer is sized by this whatever point_count asks for.
inline constexpr std::size_t kMaximumGraphPoints = 128;
// Telemetry sources one text widget composes into a single string. Raising this grows the per-widget document storage, the widget render state, and the binder arrays.
inline constexpr std::size_t kMaximumTextSources = 3;
// Value modifiers per text widget source.
inline constexpr std::size_t kMaximumValueModifiers = 4;
// Stops in one widget colour ramp. Four is a normal, caution, warning and limit band, the same bands the conditional rules cover discretely.
inline constexpr std::size_t kMaximumColorStops = 4;
// Conditional styling rules per widget. Four covers a normal, caution, warning and limit band.
inline constexpr std::size_t kMaximumWidgetConditions = 4;
// Uploaded image identifier storage including the terminator (31 usable bytes). Must match kImageIdCapacity in the image contract.
inline constexpr std::size_t kImageIdCapacity = 32;
// Widget identifier storage including the terminator (15 usable bytes).
inline constexpr std::size_t kWidgetIdCapacity = 16;
// Widget title text storage including the terminator (15 usable bytes).
inline constexpr std::size_t kWidgetTitleCapacity = 16;
// Placeholder text storage including the terminator (15 usable bytes).
inline constexpr std::size_t kUnavailableTextCapacity = 16;
// Storage for the dotted property path reported with a rejection, including the terminator.
inline constexpr std::size_t kValidationPathCapacity = 48;
// Canonical telemetry field name storage including the terminator (39 usable bytes). Must match CANONICAL_NAME_CAPACITY in tools/generate_telemetry_catalog.py.
inline constexpr std::size_t kValueBindingCapacity = 40;
// Transform prefix and suffix storage including the terminator (15 usable bytes).
inline constexpr std::size_t kValueAffixCapacity = 16;

// Immutable hardware identity. Must match the firmware build or the configuration is rejected.
enum class BoardId : std::uint8_t {
  t_display_s3,
  guition_esp32_4848s040,
  guition_jc1060p470c,
};

// Telemetry transport selection. board_default defers to the immutable board descriptor.
enum class TelemetryTransportId : std::uint8_t {
  board_default,
  native_usb_cdc,
  uart,
};

// Horizontal alignment: which edge of the box the text is anchored to. Used for a text widget's value inside its content area and for a frame caption along its outer box.
enum class TextAlignment : std::uint8_t {
  left,
  center,
  right,
};

// Presentation transform applied after the modifier pipeline.
enum class ValueTransformType : std::uint8_t {
  none,
  time,
  number,
};

// Axis a linear gradient runs along. Only used when a gradient colour is set.
enum class GradientDirection : std::uint8_t {
  horizontal,
  vertical,
};

// Which part of a widget the colour ramp paints. What content means is the widget type's own business: text paints its label, a bar its fill.
enum class ColorRampTarget : std::uint8_t {
  content,
  background,
  border,
};

// Comparison a styling rule applies to the numeric value of its condition source.
enum class ConditionOperator : std::uint8_t {
  above,
  at_or_above,
  below,
  at_or_below,
  equal,
  not_equal,
};

// What a tap on a widget or a group does. none is the default and leaves the object refusing input, which is what every widget did before actions existed.
enum class WidgetActionType : std::uint8_t {
  none,
  next_screen,
  previous_screen,
  goto_screen,
};

// Stateful value processing implemented by a module behind the pipeline callback.
enum class ValueModifierType : std::uint8_t {
  lap_timer,
};

// Axis a bar fills along. A vertical bar grows upwards unless it is inverted.
enum class BarOrientation : std::uint8_t {
  horizontal,
  vertical,
};

// Outline a shape widget takes. A line is a thin rectangle, so it needs no kind of its own.
enum class ShapeKind : std::uint8_t {
  rectangle,
  ellipse,
};

// Widget kind discriminator. Selects the compile-time widget descriptor used to build the widget.
enum class WidgetType : std::uint8_t {
  text,
  shape,
  bar,
  arc,
  indicator,
  graph,
  image,
};

struct BoardConfiguration {
  BoardId id{BoardId::t_display_s3};
};

// Reserved bounded peripheral section. No user-configurable peripheral
// driver has a complete production contract yet, so a non-empty list is
// rejected rather than guessed.
struct HardwareConfiguration {
  std::uint8_t device_count{};
};

struct UartTelemetryConfiguration {
  int port{};
  int tx_pin{43};
  int rx_pin{44};
  std::uint32_t baud_rate{921600};
  bool silence_esp_logs{true};
};

struct TelemetryTransportConfiguration {
  TelemetryTransportId id{TelemetryTransportId::board_default};
  UartTelemetryConfiguration uart{};
};

// Absolute geometry in logical screen pixels.
struct WidgetPlacement {
  std::int32_t x{};
  std::int32_t y{};
  std::int32_t width{};
  std::int32_t height{};
};

struct WidgetInsets {
  std::uint16_t left{};
  std::uint16_t top{};
  std::uint16_t right{};
  std::uint16_t bottom{};
};

struct WidgetBorder {
  std::uint32_t color{0xAEAEAE};
  std::uint16_t width_px{};
  std::uint16_t radius_px{};
};

// The caption on a widget's frame. It is anchored to an edge of the
// widget's outer box, moved from there by the offsets, and it cuts the
// frame line on whichever border it ends up crossing.
struct WidgetTitleStyle {
  std::array<char, kWidgetTitleCapacity> text{};
  font_assets::FontSpec font{};
  std::uint32_t color{0xE8E8E8};
  TextAlignment alignment{TextAlignment::center};
  std::int16_t offset_x_px{};
  std::int16_t offset_y_px{};
  bool border_gap{true};
  std::uint16_t gap_padding_px{4};
};

struct WidgetValueStyle {
  font_assets::FontSpec font{};
  std::uint32_t color{0xE8E8E8};
  TextAlignment alignment{TextAlignment::center};
  std::array<char, kUnavailableTextCapacity> unavailable_text{};
};

// Stateless presentation transform. Absent means no transform is applied.
// The prefix and suffix belong to the transform rather than to one type, so
// they also apply to an untransformed value.
struct ValueTransform {
  ValueTransformType type{ValueTransformType::none};
  transformers::time_transform::Config time{};
  transformers::number_transform::Config number{};
  std::array<char, kValueAffixCapacity> prefix{};
  std::array<char, kValueAffixCapacity> suffix{};
};

struct ValueModifier {
  ValueModifierType type{ValueModifierType::lap_timer};
};

// A canonical telemetry binding with its modifier pipeline, consumed as a
// typed value. Carries no transform: the widgets that read one map it
// through a range or compare it, rather than presenting it as text.
struct ValueSourceConfiguration {
  std::array<char, kValueBindingCapacity> binding{};
  std::uint8_t modifier_count{};
  std::array<ValueModifier, kMaximumValueModifiers> modifiers{};
};

// One anchor of a colour ramp.
struct ColorStop {
  float at{};
  std::uint32_t color{0xE8E8E8};
};

// A colour interpolated from the watched source rather than switched by a
// threshold. It is the base layer: a matching rule paints over it, and with
// no stops the authored colour stands.
struct ColorRamp {
  ColorRampTarget target{ColorRampTarget::content};
  std::uint8_t stop_count{};
  std::array<ColorStop, kMaximumColorStops> stops{};
};

// Navigation a tap performs. Carried by a widget and by a group, so a tap
// target is either a readout that doubles as a button or a rectangle of the
// screen — including an empty group, which is an invisible touch zone.
struct WidgetAction {
  WidgetActionType type{WidgetActionType::none};
  std::array<char, kWidgetIdCapacity> screen{};
};

// One styling rule. The first rule whose comparison holds describes the
// widget; whatever it leaves unset stays as the widget's static style, and
// a transparent colour means unset rather than see-through.
struct WidgetCondition {
  ConditionOperator op{ConditionOperator::at_or_above};
  float value{};
  std::uint32_t color{kTransparentColor};
  std::uint32_t background_color{kTransparentColor};
  std::uint32_t border_color{kTransparentColor};
  bool hidden{false};
  std::uint16_t blink_ms{};
  std::uint16_t hold_ms{};
};

// One canonical telemetry source of a text widget, consumed through a
// pre-bound typed callback. Its transform affixes are what separate it from
// the next source, so composing several needs no format string.
struct TextSourceConfiguration {
  std::array<char, kValueBindingCapacity> binding{'v', 'e', 'h', 'i', 'c', 'l', 'e', '.', 's', 'p', 'e', 'e', 'd', '\0'};
  std::uint8_t modifier_count{};
  std::array<ValueModifier, kMaximumValueModifiers> modifiers{};
  ValueTransform transform{};
};

// What every widget type owns regardless of what it draws: where it sits,
// how it is boxed, and the rules that restyle it. Flattened into each
// widget, so these are plain widget properties on the wire.
struct WidgetFrame {
  std::array<char, kWidgetIdCapacity> id{};
  WidgetPlacement placement{};
  std::int16_t z_index{};
  WidgetInsets padding{};
  WidgetBorder border{};
  WidgetTitleStyle title{};
  std::uint32_t background_color{kTransparentColor};
  std::uint32_t background_grad_color{kTransparentColor};
  GradientDirection background_grad_dir{GradientDirection::vertical};
  std::uint16_t background_inset_px{};
  WidgetAction action{};
  ValueSourceConfiguration condition_source{};
  ColorRamp color_ramp{};
  std::uint8_t condition_count{};
  std::uint8_t screen_index{};
  std::uint8_t group_index{};
  bool group_present{false};
  std::array<WidgetCondition, kMaximumWidgetConditions> conditions{};
};

// Reusable telemetry text widget. Renders its ordered sources as one
// string.
struct TextWidgetConfiguration {
  WidgetFrame frame{};
  std::uint8_t source_count{};
  std::array<TextSourceConfiguration, kMaximumTextSources> sources{};
  WidgetValueStyle value{};
};

// Input window a widget maps its source through. The fraction is clamped,
// so a value outside the window reads as full or empty rather than
// overflowing.
struct ValueRange {
  float minimum{};
  float maximum{1.0F};
};

// One telemetry source drawn as a filled proportion of the widget. The
// frame background is the track the fill runs over, so a bar needs no track
// colour of its own.
struct BarWidgetConfiguration {
  WidgetFrame frame{};
  ValueSourceConfiguration source{};
  ValueRange range{};
  float origin{};
  bool origin_present{false};
  BarOrientation orientation{BarOrientation::horizontal};
  bool inverted{false};
  std::uint32_t fill_color{0x38BDF8};
  std::uint32_t fill_grad_color{kTransparentColor};
};

// One telemetry source swept around an arc. The track is the arc's own
// background, so a gauge needs no shape behind it.
struct ArcWidgetConfiguration {
  WidgetFrame frame{};
  ValueSourceConfiguration source{};
  ValueRange range{};
  std::uint16_t start_angle_deg{135};
  std::uint16_t sweep_deg{270};
  std::uint16_t thickness_px{8};
  std::uint32_t track_color{kTransparentColor};
  std::uint32_t fill_color{0x38BDF8};
  bool inverted{false};
};

// One lamp in an indicator strip.
struct IndicatorSegment {
  float threshold{};
  std::uint32_t color{0x00C853};
};

// A row of lamps that light as one telemetry source climbs its range: shift
// lights, a rev strip, a stint marker.
struct IndicatorWidgetConfiguration {
  WidgetFrame frame{};
  ValueSourceConfiguration source{};
  ValueRange range{};
  BarOrientation orientation{BarOrientation::horizontal};
  std::uint16_t segment_gap_px{4};
  std::uint16_t segment_radius_px{};
  std::uint32_t off_color{kTransparentColor};
  float blink_threshold{2.0F};
  std::uint16_t blink_ms{};
  std::uint8_t segment_count{};
  std::array<IndicatorSegment, kMaximumIndicatorSegments> segments{};
};

// A rolling trace of one telemetry source. The history is presentation
// state the widget samples for itself; it is not a telemetry value and
// nothing else can read it.
struct GraphWidgetConfiguration {
  WidgetFrame frame{};
  ValueSourceConfiguration source{};
  ValueRange range{};
  std::uint16_t point_count{64};
  std::uint16_t sample_interval_ms{100};
  std::uint32_t line_color{0x38BDF8};
  std::uint16_t line_width_px{2};
};

// An uploaded image drawn inside the frame. It binds no telemetry of its
// own, but its styling rules can hide it, flash it or recolour it. Neither
// scaled nor rotated: the configurator converts each image to the size it
// is drawn at, which also keeps the accelerated draw path on the ESP32-P4.
struct ImageWidgetConfiguration {
  WidgetFrame frame{};
  std::array<char, kImageIdCapacity> image{};
  std::uint32_t recolor{kTransparentColor};
  std::uint8_t recolor_opa{255};
};

// Panels, dividers and backing plates: the frame is the whole widget. It
// binds no telemetry of its own, but its styling rules can still hide it or
// flash it. A line is a thin rectangle.
struct ShapeWidgetConfiguration {
  WidgetFrame frame{};
  ShapeKind kind{ShapeKind::rectangle};
};

// Declaration-order reference into the typed widget storage of one screen.
// Carries the ordering keys so compositing needs no widget-type knowledge:
// z_index ascending, authored array order breaking ties.
struct WidgetReference {
  WidgetType type{WidgetType::text};
  std::uint8_t index{};
  std::int16_t z_index{};
};

// One activation rule for a group in a slot. The first rule whose
// comparison holds shows its group, and the hold keeps it up for that long
// after the match ends so a momentary event stays readable.
struct GroupCondition {
  ConditionOperator op{ConditionOperator::at_or_above};
  float value{};
  std::uint16_t hold_ms{};
};

// A rectangle of a screen with widgets authored inside it. A widget in a
// group is placed relative to this box and clipped to it; the group
// performs no layout of its own. Groups sharing a slot occupy the same box
// with one of them visible at a time.
struct GroupConfiguration {
  std::array<char, kWidgetIdCapacity> id{};
  WidgetPlacement placement{};
  std::int16_t z_index{};
  std::uint8_t slot{};
  bool slot_default{false};
  WidgetAction action{};
  ValueSourceConfiguration condition_source{};
  std::uint8_t condition_count{};
  std::uint8_t screen_index{};
  std::array<GroupCondition, kMaximumWidgetConditions> conditions{};
  std::uint8_t widget_count{};
  std::array<WidgetReference, kMaximumWidgetsPerGroup> widgets{};
};

// One dashboard screen: the coordinate space its widgets are placed in, and
// the order they stack in. The widgets themselves live in the dashboard's
// pool; a screen names them by reference. Widgets authored directly on the
// screen appear in its own reference table, and widgets authored inside a
// group appear in that group's.
struct ScreenConfiguration {
  std::array<char, kWidgetIdCapacity> id{};
  std::uint32_t background_color{0x000000};
  std::uint8_t group_count{};
  std::array<GroupConfiguration, kMaximumGroups> groups{};
  std::uint8_t widget_count{};
  std::array<WidgetReference, kMaximumWidgetsPerScreen> widgets{};
};

// Owns the typed widget storage as one pool shared by every screen; a
// screen holds only an ordered list of references into it. A screen
// therefore costs its reference table rather than a full set of widget
// arrays.
struct DashboardConfiguration {
  std::uint8_t screen_count{};
  std::array<ScreenConfiguration, kMaximumScreens> screens{};
  std::uint8_t text_widget_count{};
  std::array<TextWidgetConfiguration, kMaximumTextWidgets> text_widgets{};
  std::uint8_t shape_widget_count{};
  std::array<ShapeWidgetConfiguration, kMaximumShapeWidgets> shape_widgets{};
  std::uint8_t bar_widget_count{};
  std::array<BarWidgetConfiguration, kMaximumBarWidgets> bar_widgets{};
  std::uint8_t arc_widget_count{};
  std::array<ArcWidgetConfiguration, kMaximumArcWidgets> arc_widgets{};
  std::uint8_t indicator_widget_count{};
  std::array<IndicatorWidgetConfiguration, kMaximumIndicatorWidgets> indicator_widgets{};
  std::uint8_t graph_widget_count{};
  std::array<GraphWidgetConfiguration, kMaximumGraphWidgets> graph_widgets{};
  std::uint8_t image_widget_count{};
  std::array<ImageWidgetConfiguration, kMaximumImageWidgets> image_widgets{};
};

struct ApplicationConfiguration {
  BoardConfiguration board{};
  HardwareConfiguration hardware{};
  bool telemetry_transport_present{false};
  TelemetryTransportConfiguration telemetry_transport{};
  DashboardConfiguration dashboard{};
};

// Wire spellings and their conversions. Both directions read the same
// generated value list the parser allow-lists use, so a name cannot drift
// between the contract, the parser, and the configurator.

inline constexpr std::array<std::string_view, 3> kBoardIdNames{{
    "t_display_s3",
    "guition_esp32_4848s040",
    "guition_jc1060p470c",
}};

[[nodiscard]] inline std::string_view board_id_name(const BoardId value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kBoardIdNames.size() ? kBoardIdNames[index] : std::string_view{};
}

[[nodiscard]] inline bool board_id_from_name(const std::string_view name,
                                                  BoardId& value) {
  for (std::size_t index = 0; index < kBoardIdNames.size(); ++index) {
    if (kBoardIdNames[index] == name) {
      value = static_cast<BoardId>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 3> kTelemetryTransportIdNames{{
    "board_default",
    "native_usb_cdc",
    "uart",
}};

[[nodiscard]] inline std::string_view telemetry_transport_id_name(const TelemetryTransportId value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kTelemetryTransportIdNames.size() ? kTelemetryTransportIdNames[index] : std::string_view{};
}

[[nodiscard]] inline bool telemetry_transport_id_from_name(const std::string_view name,
                                                  TelemetryTransportId& value) {
  for (std::size_t index = 0; index < kTelemetryTransportIdNames.size(); ++index) {
    if (kTelemetryTransportIdNames[index] == name) {
      value = static_cast<TelemetryTransportId>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 3> kTextAlignmentNames{{
    "left",
    "center",
    "right",
}};

[[nodiscard]] inline std::string_view text_alignment_name(const TextAlignment value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kTextAlignmentNames.size() ? kTextAlignmentNames[index] : std::string_view{};
}

[[nodiscard]] inline bool text_alignment_from_name(const std::string_view name,
                                                  TextAlignment& value) {
  for (std::size_t index = 0; index < kTextAlignmentNames.size(); ++index) {
    if (kTextAlignmentNames[index] == name) {
      value = static_cast<TextAlignment>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 3> kValueTransformTypeNames{{
    "none",
    "time",
    "number",
}};

[[nodiscard]] inline std::string_view value_transform_type_name(const ValueTransformType value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kValueTransformTypeNames.size() ? kValueTransformTypeNames[index] : std::string_view{};
}

[[nodiscard]] inline bool value_transform_type_from_name(const std::string_view name,
                                                  ValueTransformType& value) {
  for (std::size_t index = 0; index < kValueTransformTypeNames.size(); ++index) {
    if (kValueTransformTypeNames[index] == name) {
      value = static_cast<ValueTransformType>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 2> kGradientDirectionNames{{
    "horizontal",
    "vertical",
}};

[[nodiscard]] inline std::string_view gradient_direction_name(const GradientDirection value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kGradientDirectionNames.size() ? kGradientDirectionNames[index] : std::string_view{};
}

[[nodiscard]] inline bool gradient_direction_from_name(const std::string_view name,
                                                  GradientDirection& value) {
  for (std::size_t index = 0; index < kGradientDirectionNames.size(); ++index) {
    if (kGradientDirectionNames[index] == name) {
      value = static_cast<GradientDirection>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 3> kColorRampTargetNames{{
    "content",
    "background",
    "border",
}};

[[nodiscard]] inline std::string_view color_ramp_target_name(const ColorRampTarget value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kColorRampTargetNames.size() ? kColorRampTargetNames[index] : std::string_view{};
}

[[nodiscard]] inline bool color_ramp_target_from_name(const std::string_view name,
                                                  ColorRampTarget& value) {
  for (std::size_t index = 0; index < kColorRampTargetNames.size(); ++index) {
    if (kColorRampTargetNames[index] == name) {
      value = static_cast<ColorRampTarget>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 6> kConditionOperatorNames{{
    "above",
    "at_or_above",
    "below",
    "at_or_below",
    "equal",
    "not_equal",
}};

[[nodiscard]] inline std::string_view condition_operator_name(const ConditionOperator value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kConditionOperatorNames.size() ? kConditionOperatorNames[index] : std::string_view{};
}

[[nodiscard]] inline bool condition_operator_from_name(const std::string_view name,
                                                  ConditionOperator& value) {
  for (std::size_t index = 0; index < kConditionOperatorNames.size(); ++index) {
    if (kConditionOperatorNames[index] == name) {
      value = static_cast<ConditionOperator>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 4> kWidgetActionTypeNames{{
    "none",
    "next_screen",
    "previous_screen",
    "goto_screen",
}};

[[nodiscard]] inline std::string_view widget_action_type_name(const WidgetActionType value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kWidgetActionTypeNames.size() ? kWidgetActionTypeNames[index] : std::string_view{};
}

[[nodiscard]] inline bool widget_action_type_from_name(const std::string_view name,
                                                  WidgetActionType& value) {
  for (std::size_t index = 0; index < kWidgetActionTypeNames.size(); ++index) {
    if (kWidgetActionTypeNames[index] == name) {
      value = static_cast<WidgetActionType>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 1> kValueModifierTypeNames{{
    "lap_timer",
}};

[[nodiscard]] inline std::string_view value_modifier_type_name(const ValueModifierType value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kValueModifierTypeNames.size() ? kValueModifierTypeNames[index] : std::string_view{};
}

[[nodiscard]] inline bool value_modifier_type_from_name(const std::string_view name,
                                                  ValueModifierType& value) {
  for (std::size_t index = 0; index < kValueModifierTypeNames.size(); ++index) {
    if (kValueModifierTypeNames[index] == name) {
      value = static_cast<ValueModifierType>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 2> kBarOrientationNames{{
    "horizontal",
    "vertical",
}};

[[nodiscard]] inline std::string_view bar_orientation_name(const BarOrientation value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kBarOrientationNames.size() ? kBarOrientationNames[index] : std::string_view{};
}

[[nodiscard]] inline bool bar_orientation_from_name(const std::string_view name,
                                                  BarOrientation& value) {
  for (std::size_t index = 0; index < kBarOrientationNames.size(); ++index) {
    if (kBarOrientationNames[index] == name) {
      value = static_cast<BarOrientation>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 2> kShapeKindNames{{
    "rectangle",
    "ellipse",
}};

[[nodiscard]] inline std::string_view shape_kind_name(const ShapeKind value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kShapeKindNames.size() ? kShapeKindNames[index] : std::string_view{};
}

[[nodiscard]] inline bool shape_kind_from_name(const std::string_view name,
                                                  ShapeKind& value) {
  for (std::size_t index = 0; index < kShapeKindNames.size(); ++index) {
    if (kShapeKindNames[index] == name) {
      value = static_cast<ShapeKind>(index);
      return true;
    }
  }
  return false;
}

inline constexpr std::array<std::string_view, 7> kWidgetTypeNames{{
    "text",
    "shape",
    "bar",
    "arc",
    "indicator",
    "graph",
    "image",
}};

[[nodiscard]] inline std::string_view widget_type_name(const WidgetType value) {
  const auto index = static_cast<std::size_t>(value);
  return index < kWidgetTypeNames.size() ? kWidgetTypeNames[index] : std::string_view{};
}

[[nodiscard]] inline bool widget_type_from_name(const std::string_view name,
                                                  WidgetType& value) {
  for (std::size_t index = 0; index < kWidgetTypeNames.size(); ++index) {
    if (kWidgetTypeNames[index] == name) {
      value = static_cast<WidgetType>(index);
      return true;
    }
  }
  return false;
}

// Uniform access to the storage one widget type occupies in a document.
// Anything that has to do the same thing for every type — composing,
// parsing, comparing two documents, warming fonts — walks this table
// rather than naming each type, so adding a widget type is a schema
// change and not an edit in every such place.
struct WidgetTypeTraits {
  WidgetType type{};
  std::string_view name{};
  // The document property its pool is stored under, which is what a
  // capacity rejection has to name.
  std::string_view storage_key{};
  // Instances of this type one document can hold.
  std::size_t capacity{};
  std::uint8_t (*count)(const DashboardConfiguration&){};
  void (*set_count)(DashboardConfiguration&, std::uint8_t){};
  // Null past the count, so a caller cannot reach an instance the
  // document does not have.
  const WidgetFrame* (*frame)(const DashboardConfiguration&,
                              std::uint8_t){};
  WidgetFrame* (*mutable_frame)(DashboardConfiguration&, std::uint8_t){};
  // One instance as raw bytes, for the byte compare that decides whether
  // a widget changed between two documents. Empty past the count, so two
  // absent instances compare equal.
  std::span<const std::byte> (*element_bytes)(const DashboardConfiguration&,
                                              std::uint8_t){};
};

inline constexpr std::array<WidgetTypeTraits, 7> kWidgetTypeTraits{{
    {
        .type = WidgetType::text,
        .name = "text",
        .storage_key = "text_widgets",
        .capacity = kMaximumTextWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.text_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.text_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.text_widget_count
                     ? &dashboard.text_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.text_widget_count
                     ? &dashboard.text_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.text_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.text_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::shape,
        .name = "shape",
        .storage_key = "shape_widgets",
        .capacity = kMaximumShapeWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.shape_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.shape_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.shape_widget_count
                     ? &dashboard.shape_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.shape_widget_count
                     ? &dashboard.shape_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.shape_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.shape_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::bar,
        .name = "bar",
        .storage_key = "bar_widgets",
        .capacity = kMaximumBarWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.bar_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.bar_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.bar_widget_count
                     ? &dashboard.bar_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.bar_widget_count
                     ? &dashboard.bar_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.bar_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.bar_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::arc,
        .name = "arc",
        .storage_key = "arc_widgets",
        .capacity = kMaximumArcWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.arc_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.arc_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.arc_widget_count
                     ? &dashboard.arc_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.arc_widget_count
                     ? &dashboard.arc_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.arc_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.arc_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::indicator,
        .name = "indicator",
        .storage_key = "indicator_widgets",
        .capacity = kMaximumIndicatorWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.indicator_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.indicator_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.indicator_widget_count
                     ? &dashboard.indicator_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.indicator_widget_count
                     ? &dashboard.indicator_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.indicator_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.indicator_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::graph,
        .name = "graph",
        .storage_key = "graph_widgets",
        .capacity = kMaximumGraphWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.graph_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.graph_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.graph_widget_count
                     ? &dashboard.graph_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.graph_widget_count
                     ? &dashboard.graph_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.graph_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.graph_widgets[index], 1});
        },
    },
    {
        .type = WidgetType::image,
        .name = "image",
        .storage_key = "image_widgets",
        .capacity = kMaximumImageWidgets,
        .count = [](const DashboardConfiguration& dashboard)
            -> std::uint8_t { return dashboard.image_widget_count; },
        .set_count = [](DashboardConfiguration& dashboard,
                        const std::uint8_t value) {
          dashboard.image_widget_count = value;
        },
        .frame = [](const DashboardConfiguration& dashboard,
                    const std::uint8_t index) -> const WidgetFrame* {
          return index < dashboard.image_widget_count
                     ? &dashboard.image_widgets[index].frame
                     : nullptr;
        },
        .mutable_frame = [](DashboardConfiguration& dashboard,
                            const std::uint8_t index) -> WidgetFrame* {
          return index < dashboard.image_widget_count
                     ? &dashboard.image_widgets[index].frame
                     : nullptr;
        },
        .element_bytes =
            [](const DashboardConfiguration& dashboard,
               const std::uint8_t index) -> std::span<const std::byte> {
          if (index >= dashboard.image_widget_count) {
            return {};
          }
          return std::as_bytes(std::span{&dashboard.image_widgets[index], 1});
        },
    },
}};

// A WidgetType always comes from the parser or from a reference the
// parser wrote, so it is always in range; the guard keeps a corrupted
// value from indexing past the table rather than reporting an error no
// caller could act on.
[[nodiscard]] inline const WidgetTypeTraits& widget_traits(
    const WidgetType type) {
  const auto index = static_cast<std::size_t>(type);
  return index < kWidgetTypeTraits.size() ? kWidgetTypeTraits[index]
                                         : kWidgetTypeTraits[0];
}

}  // namespace simcore::configuration
