#pragma once

#include "sdkconfig.h"

#ifdef CONFIG_PITRIG_DEBUG
#define PITRIG_DEBUG 1
#else
#define PITRIG_DEBUG 0
#endif
#ifdef CONFIG_PITRIG_LAYOUT_DEBUG
#define PITRIG_LAYOUT_DEBUG 1
#else
#define PITRIG_LAYOUT_DEBUG 0
#endif
#ifdef CONFIG_PITRIG_DEBUG_OVERLAY_FULL
#define PITRIG_DEBUG_OVERLAY_FULL 1
#else
#define PITRIG_DEBUG_OVERLAY_FULL 0
#endif
#ifdef CONFIG_PITRIG_DEBUG_OVERLAY_FPS
#define PITRIG_DEBUG_OVERLAY_FPS 1
#else
#define PITRIG_DEBUG_OVERLAY_FPS 0
#endif
#define PITRIG_DEBUG_OVERLAY \
  (PITRIG_DEBUG && (PITRIG_DEBUG_OVERLAY_FULL || PITRIG_DEBUG_OVERLAY_FPS))
#ifdef CONFIG_PITRIG_LOG_MODE_FULL
#define PITRIG_LOG_MODE_FULL 1
#else
#define PITRIG_LOG_MODE_FULL 0
#endif
#ifdef CONFIG_PITRIG_DISPLAY_RENDER_DIRECT
#define PITRIG_DISPLAY_RENDER_DIRECT 1
#else
#define PITRIG_DISPLAY_RENDER_DIRECT 0
#endif

#ifdef CONFIG_PITRIG_DISPLAY_RENDER_FULL
#define PITRIG_DISPLAY_RENDER_FULL 1
#else
#define PITRIG_DISPLAY_RENDER_FULL 0
#endif

#ifdef CONFIG_PITRIG_DISPLAY_RENDER_FULL_STRIPS
#define PITRIG_DISPLAY_RENDER_FULL_STRIPS 1
#else
#define PITRIG_DISPLAY_RENDER_FULL_STRIPS 0
#endif

#ifdef CONFIG_PITRIG_DISPLAY_COLOR_24BIT
#define PITRIG_DISPLAY_COLOR_24BIT 1
#else
#define PITRIG_DISPLAY_COLOR_24BIT 0
#endif

#ifdef CONFIG_PITRIG_DISPLAY_VSYNC_LOCK
#define PITRIG_DISPLAY_VSYNC_LOCK 1
#else
#define PITRIG_DISPLAY_VSYNC_LOCK 0
#endif

#define PITRIG_DISPLAY_RENDER_TEAR_FREE \
  (PITRIG_DISPLAY_RENDER_DIRECT || PITRIG_DISPLAY_RENDER_FULL || PITRIG_DISPLAY_RENDER_FULL_STRIPS)

#define PITRIG_COMMUNICATION_CORE 0
#define PITRIG_RENDER_CORE 1
